import test from 'node:test';
import assert from 'node:assert/strict';
import {createGameAudio} from '../public/src/audio.js';
function setup(){const sounds=[];let time=0;function make(src){const a={src,currentTime:0,listeners:{},plays:0,pauses:0,addEventListener(k,f){this.listeners[k]=f;},play(){this.plays++;return Promise.resolve();},pause(){this.pauses++;},load(){},cloneNode(){return make(src);}};sounds.push(a);return a;}return {sounds,sound:createGameAudio(make,()=>time),tick:n=>time+=n};}
const battle=units=>({units,buildings:[],pauseRemaining:0,serverPaused:false});
test('music waits for interaction, switches scenes and suspends when hidden',()=>{const {sound,sounds}=setup();sound.scene('battle');assert.equal(sounds.reduce((n,a)=>n+a.plays,0),0);sound.unlock();const fight=sounds.find(a=>a.src.endsWith('bgm-battle.mp3'));assert.equal(fight.plays,1);assert.equal(fight.loop,true);sound.scene('home');const home=sounds.find(a=>a.src.endsWith('bgm-home.mp3'));assert.equal(home,fight);assert.ok(fight.pauses>0);assert.equal(home.plays,2);sound.visibility(true);assert.ok(home.pauses>0);sound.visibility(false);assert.equal(home.plays,3);});
test('actual hits and deaths play once per snapshot and damage is throttled',()=>{const {sound,sounds,tick}=setup();sound.unlock();sound.begin(battle([{id:1,hp:100}]));sound.update(battle([{id:1,hp:80,hurtAt:1}]));sound.update(battle([{id:1,hp:80,hurtAt:1}]));assert.equal(sounds.filter(a=>a.src.endsWith('sfx-hit.mp3')).reduce((n,a)=>n+a.plays,0),1);tick(200);sound.update(battle([{id:1,hp:0,hurtAt:2}]));sound.update(battle([]));assert.equal(sounds.filter(a=>a.src.endsWith('sfx-death.mp3')).reduce((n,a)=>n+a.plays,0),1);});
test('server snapshots detect removed troops without replaying old deaths or buildings',()=>{const {sound,sounds}=setup();sound.unlock();sound.begin({units:[{id:1,hp:100},{id:2,hp:0}],buildings:[{id:3,hp:100,castle:true}]});sound.update(battle([]));sound.update(battle([]));assert.equal(sounds.filter(a=>a.src.endsWith('sfx-death.mp3')).reduce((n,a)=>n+a.plays,0),1);sound.begin({units:[],buildings:[{id:3,hp:100,castle:true}]});sound.update(battle([]));assert.equal(sounds.filter(a=>a.src.endsWith('sfx-death.mp3')).reduce((n,a)=>n+a.plays,0),1);});
test('pause suppresses combat sounds and results use the local winner',()=>{const {sound,sounds,tick}=setup();sound.unlock();sound.begin(battle([{id:1,hp:100}]));sound.update({...battle([{id:1,hp:0,hurtAt:1}]),serverPaused:true});assert.equal(sounds.some(a=>a.src.includes('sfx-')),false);sound.result(0);assert.equal(sounds.filter(a=>a.src.endsWith('sfx-victory.mp3')).reduce((n,a)=>n+a.plays,0),1);tick(1500);sound.result(1);assert.equal(sounds.filter(a=>a.src.endsWith('sfx-defeat.mp3')).reduce((n,a)=>n+a.plays,0),1);sound.result(-1);assert.equal(sounds.some(a=>a.src.includes('draw')),false);});
