import test from 'node:test';
import assert from 'node:assert/strict';
import worker,{Accounts,Match} from '../src/worker.js';
import {campaignPeriod,newCampaign} from '../src/campaign.js';
import {defaultDeck} from '../public/src/data.js';
class Storage{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k));}async put(k,v){this.data.set(k,structuredClone(v));}async delete(k){this.data.delete(k);}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async transaction(fn){const prior=this.lock||Promise.resolve();let release;this.lock=new Promise(r=>release=r);await prior;const backup=structuredClone(this.data);try{return await fn(this);}catch(e){this.data=backup;throw e;}finally{release();}}async setAlarm(t){this.alarm=t;}}
const request=(op,d)=>new Request('https://internal/'+op,{method:'POST',body:JSON.stringify(d)});
function setup(){const storage=new Storage(),env={},ctx={storage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},accounts=new Accounts(ctx,env);env.ACCOUNTS={idFromName:x=>x,get:()=>({fetch:(url,init)=>accounts.fetch(new Request(url,init))})};env.APP_ORIGIN='https://samkok-showdown.redfisharthur.workers.dev';return {storage,env,ctx,accounts};}
test('backend requires a session, rejects cross-origin writes and reports unconfigured LINE',async()=>{const {env}=setup();let r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/me'),env);assert.equal(r.status,401);r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/profile',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),env);assert.equal(r.status,403);r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/auth/line'),env);assert.equal(r.status,503);});
test('cloud profiles validate decks, enforce transfer cooldown and count only cloud users',async()=>{const {accounts}=setup();await accounts.fetch(request('login',{id:'a',name:'A',picture:'',session:'one'}));let r=await accounts.fetch(request('profile',{id:'a',faction:'shu',decks:{shu:defaultDeck('shu')}}));assert.equal(r.status,200);r=await accounts.fetch(request('profile',{id:'a',faction:'shu',decks:{shu:['spear']}}));assert.equal(r.status,400);r=await accounts.fetch(request('world',{}));assert.equal((await r.json()).factions.shu.players,1);await accounts.fetch(request('profile',{id:'a',faction:'wei'}));r=await accounts.fetch(request('profile',{id:'a',faction:'wu'}));assert.equal(r.status,400);});
test('matched humans check membership, hides opponent hand and simulates on server',async()=>{const {env,storage:accountStorage}=setup(),storage=new Storage(),ctx={storage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},m=new Match(ctx,env);await ctx.ready;const a={id:'a',name:'A',faction:'shu',decks:{shu:defaultDeck('shu')}},b={id:'b',name:'B',faction:'wei',decks:{wei:defaultDeck('wei')}},room={id:'room',host:a,guest:b,status:'waiting',readyDeadline:Date.now()+30000,expires:Date.now()+600000};await accountStorage.put('room:room',room);let r=await m.fetch(request('state',{room,user:a}));assert.equal((await r.json()).battle,null);await m.fetch(request('ready',{room,user:a}));assert.equal(m.battle,null);r=await m.fetch(request('ready',{room,user:b}));const d=await r.json();assert.equal(d.side,1);assert.equal(d.battle.sides[0].queue.length,0);assert.equal(d.battle.sides[1].queue.length,8);r=await m.fetch(request('state',{room,user:{id:'c'}}));assert.equal(r.status,403);await m.alarm();assert.ok(m.battle.elapsed>0);const count=m.battle.units.length;for(let i=0;i<20;i++)await m.alarm();assert.equal(m.battle.units.length,count);});

test('matchmaking pairs distinct players, keeps assignments stable and supports cancellation',async()=>{const {accounts}=setup();const a={id:'a',faction:'shu'},b={id:'b',faction:'wei'},c={id:'c',faction:'wu'};const queue=async user=>(await accounts.fetch(request('matchmaking',{user}))).json();assert.equal((await queue(a)).matched,false);assert.equal((await queue(a)).matched,false);const pair=await queue(b);assert.equal(pair.matched,true);assert.equal((await queue(a)).id,pair.id);assert.equal((await queue(b)).id,pair.id);assert.equal((await queue(c)).matched,false);assert.equal((await (await accounts.fetch(request('cancel',{user:c}))).json()).cancelled,true);assert.equal((await queue({id:'d',faction:'qun'})).matched,false);});
test('expired queue entries never become opponents',async()=>{const {accounts,storage}=setup();await storage.put('queue:old',{user:{id:'old'},expires:Date.now()-1});const d=await (await accounts.fetch(request('matchmaking',{user:{id:'new',faction:'shu'}}))).json();assert.equal(d.matched,false);assert.equal(await storage.get('queue:old'),undefined);});

test('world starts neutral and reads weekly server state instead of legacy or AI scores',async()=>{const {accounts,storage}=setup();await storage.put('user:a',{id:'a',faction:'shu',contribution:999});await storage.put('user:b',{id:'b',faction:'wu',contribution:0,records:[{winner:0}]});let d=await (await accounts.fetch(request('world',{}))).json();assert.equal(d.territory.neutral,10000);assert.equal(d.strength.shu,0);const c=newCampaign();c.factions.shu.contribution=30;c.factions.wei.contribution=10;c.provinces[0].owner='shu';await storage.put('campaign:'+c.id,c);d=await (await accounts.fetch(request('world',{}))).json();assert.deepEqual(d.strength,{shu:7500,wei:2500,wu:0,qun:0});assert.ok(d.territory.shu>0);assert.ok(d.territory.neutral>0);});

async function humanMatch(){const state=setup(),a={id:'a',name:'A',faction:'shu',decks:{shu:defaultDeck('shu')}},b={id:'b',name:'B',faction:'wei',decks:{wei:defaultDeck('wei')}},room={id:crypto.randomUUID(),host:a,guest:b,province:'yi',status:'waiting',readyDeadline:Date.now()+30000,expires:Date.now()+600000};await state.storage.put('room:'+room.id,room);await state.storage.put('assignment:a',room.id);await state.storage.put('assignment:b',room.id);const storage=new Storage(),ctx={storage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},m=new Match(ctx,state.env);await ctx.ready;await m.fetch(request('ready',{room,user:a}));await m.fetch(request('ready',{room,user:b}));return {...state,a,b,room,m,matchStorage:storage,ctx};}
test('cancel and ready timeout release both players without starting a battle',async()=>{const {accounts,storage}=setup(),a={id:'a',faction:'shu'},b={id:'b',faction:'wei'};await accounts.fetch(request('matchmaking',{user:a}));const {id}=await (await accounts.fetch(request('matchmaking',{user:b}))).json();await accounts.fetch(request('cancel',{user:a}));assert.equal((await storage.get('room:'+id)).status,'cancelled');assert.equal(await storage.get('assignment:b'),undefined);await accounts.fetch(request('matchmaking',{user:a}));const {id:next}=await (await accounts.fetch(request('matchmaking',{user:b}))).json();const r=await storage.get('room:'+next);r.readyDeadline=Date.now()-1;await storage.put('room:'+next,r);const d=await (await accounts.fetch(request('matchmaking',{user:a}))).json();assert.equal(d.matched,false);assert.equal(await storage.get('assignment:b'),undefined);});
test('simultaneous matching pairs four unique people and retains stable assignments',async()=>{const {accounts,storage}=setup();await Promise.all(['a','b','c','d'].map(id=>accounts.fetch(request('matchmaking',{user:{id,faction:id==='a'||id==='c'?'shu':'wei'}}))));const rooms=[...(await storage.list({prefix:'room:'})).values()];assert.equal(rooms.length,2);assert.equal(new Set(rooms.flatMap(r=>[r.host.id,r.guest.id])).size,4);assert.ok(rooms.every(r=>r.host.id!==r.guest.id));});
test('actions reject stale cards and invalid locations, deduplicate retries and persist receipts',async()=>{const {m,a,room,matchStorage,env}=await humanMatch();const bad=await m.fetch(request('action',{room,user:a,action:{id:'bad',type:'play',index:0,cardId:'arrows',x:149,y:650}}));assert.equal(bad.status,409);assert.equal(m.battle.sides[0].morale,5);const good={id:'same',type:'play',index:0,cardId:'guanyu',x:149,y:650};assert.equal((await m.fetch(request('action',{room,user:a,action:good}))).status,200);assert.equal(m.battle.sides[0].morale,0);assert.equal((await (await m.fetch(request('action',{room,user:a,action:good}))).json()).duplicate,true);assert.equal(m.events.length,1);const ctx={storage:matchStorage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},restored=new Match(ctx,env);await ctx.ready;assert.equal((await (await restored.fetch(request('action',{room,user:a,action:good}))).json()).duplicate,true);assert.equal(restored.battle.sides[0].morale,0);});
test('disconnect pauses combat, reconnect resumes and grace expiry ends the match once',async()=>{const {m,a,b,room,accounts}=await humanMatch();m.lastSeen[1]=Date.now()-5000;const elapsed=m.battle.elapsed;await m.alarm();assert.equal(m.battle.elapsed,elapsed);assert.equal((await (await m.fetch(request('state',{room,user:a}))).json()).disconnect[1]<30,true);await m.fetch(request('state',{room,user:b}));await m.alarm();assert.ok(m.battle.elapsed>elapsed);m.lastSeen[1]=Date.now()-31000;await m.alarm();assert.equal(m.battle.result.winner,0);assert.equal(m.battle.result.reason,'disconnect');await m.alarm();assert.equal((await (await accounts.fetch(request('records',{id:a.id}))).json()).records.length,1);});
test('surrender ends on the server and preserves a genuine result',async()=>{const {m,a,room}=await humanMatch();const r=await m.fetch(request('action',{room,user:a,action:{id:'resign',type:'resign'}}));assert.equal(r.status,200);assert.equal(m.battle.result.winner,1);assert.equal(m.finished,true);const d=await (await m.fetch(request('state',{room,user:a}))).json();assert.equal(d.battle.result.reason,'surrender');assert.deepEqual(d.battle.result.awards,[0,0]);});
test('finish settlement is idempotent, applies rematch limits and captures a selected province',async()=>{const {accounts,storage}=setup();await storage.put('user:a',{id:'a',faction:'shu',tokens:1,changedAt:0});const finish=async(id,opponent='b')=>{await storage.put('room:'+id,{id,province:'yi',status:'playing'});return (await (await accounts.fetch(request('finish',{id,players:[{id:'a',name:'A',faction:'shu',deck:defaultDeck('shu')},{id:opponent,name:'B',faction:'wei',deck:defaultDeck('wei')}],result:{winner:0,duration:40},events:[{side:0,type:'move'},{side:1,type:'play'}]}))).json()).record;};assert.deepEqual((await finish('one')).awards,[10,2]);assert.deepEqual((await finish('one')).awards,[10,2]);assert.deepEqual((await finish('two')).awards,[5,1]);assert.deepEqual((await finish('three')).awards,[2,0]);assert.deepEqual((await finish('four')).awards,[0,0]);await finish('five','c');const captured=await finish('six','d');assert.equal(captured.war.captured,true);const d=await (await accounts.fetch(request('world',{}))).json();assert.equal(d.provinces.find(p=>p.id==='yi').owner,'shu');assert.equal(d.factions.shu.contribution,37);});
test('transfer tokens refill after thirty days and queued profiles are locked',async()=>{const {accounts,storage}=setup();await storage.put('user:a',{id:'a',faction:'shu',tokens:0,changedAt:Date.now()-31*86400000,decks:{}});const r=await accounts.fetch(request('profile',{id:'a',faction:'wei'}));assert.equal(r.status,200);assert.equal((await r.json()).user.tokens,0);const user=await storage.get('user:a');await accounts.fetch(request('matchmaking',{user}));await accounts.fetch(request('matchmaking',{user:{id:'b',faction:'wu'}}));assert.equal((await accounts.fetch(request('profile',{id:'a',faction:'wei'}))).status,409);});

test('event chunks restore completely and record pages are restricted to participants',async()=>{const {m,a,b,room,matchStorage,env,accounts}=await humanMatch();m.events=Array.from({length:230},(_,i)=>({at:i/10,side:i%2,type:'move',x:149,y:600}));await m.persist();const game=await matchStorage.get('game');assert.equal(game.events,undefined);assert.equal(game.eventCount,230);const ctx={storage:matchStorage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},restored=new Match(ctx,env);await ctx.ready;assert.deepEqual(restored.events,m.events);m.battle.elapsed=40;m.battle.finish(0);await m.finish();let d=await (await accounts.fetch(request('record-events',{userId:a.id,id:room.id,offset:0}))).json();assert.equal(d.events.length,100);assert.equal(d.next,100);d=await (await accounts.fetch(request('record-events',{userId:b.id,id:room.id,offset:200}))).json();assert.equal(d.events.length,30);assert.equal(d.next,null);assert.equal((await accounts.fetch(request('record-events',{userId:'outsider',id:room.id,offset:0}))).status,404);});
test('200 concurrent queue requests form 100 distinct automatic matches',async()=>{const {accounts,storage}=setup();await Promise.all(Array.from({length:200},(_,i)=>accounts.fetch(request('matchmaking',{user:{id:'player'+i,faction:i%2?'shu':'wei'}}))));const rooms=[...(await storage.list({prefix:'room:'})).values()];assert.equal(rooms.length,100);assert.equal(new Set(rooms.flatMap(r=>[r.host.id,r.guest.id])).size,200);});
test('server constrains both lords to their own region and records the actual destination',async()=>{const {m,a,b,room}=await humanMatch();for(const[user,y,expected]of [[a,150,490],[b,700,372]]){const r=await m.fetch(request('action',{room,user,action:{id:'region-'+user.id,type:'move',x:149,y}}));assert.equal(r.status,200);const side=user.id===a.id?0:1;assert.equal(m.battle.sides[side].lord.destination.y,expected);assert.equal(m.events.at(-1).y,expected);}for(let i=0;i<100;i++)m.battle.update(.1);assert.ok(m.battle.sides[0].lord.y>=490);assert.ok(m.battle.sides[1].lord.y<=372);});

test('guests may view national state but cannot match or write a cloud profile',async()=>{const {env,storage}=setup();const before=await (await worker.fetch(new Request(env.APP_ORIGIN+'/api/world'),env)).json();for(const path of ['matchmaking','profile']){const response=await worker.fetch(new Request(env.APP_ORIGIN+'/api/'+path,{method:'POST',headers:{Origin:env.APP_ORIGIN,'Content-Type':'application/json'},body:JSON.stringify({faction:'shu',decks:{shu:defaultDeck('shu')},contribution:9999})}),env);assert.equal(response.status,401);}const after=await (await worker.fetch(new Request(env.APP_ORIGIN+'/api/world'),env)).json();assert.deepEqual(after.factions,before.factions);assert.deepEqual(after.provinces,before.provinces);assert.equal((await storage.list({prefix:'queue:'})).size,0);assert.equal((await storage.list({prefix:'user:'})).size,0);});
