import test from 'node:test';
import assert from 'node:assert/strict';
import worker,{Accounts,Match} from '../src/worker.js';
import {defaultDeck} from '../public/src/data.js';
class Storage{constructor(){this.data=new Map();}async get(k){return structuredClone(this.data.get(k));}async put(k,v){this.data.set(k,structuredClone(v));}async delete(k){this.data.delete(k);}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async transaction(fn){return fn(this);}async setAlarm(t){this.alarm=t;}}
const request=(op,d)=>new Request('https://internal/'+op,{method:'POST',body:JSON.stringify(d)});
function setup(){const storage=new Storage(),env={},ctx={storage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},accounts=new Accounts(ctx,env);env.ACCOUNTS={idFromName:x=>x,get:()=>({fetch:(url,init)=>accounts.fetch(new Request(url,init))})};env.APP_ORIGIN='https://samkok-showdown.redfisharthur.workers.dev';return {storage,env,ctx,accounts};}
test('backend requires a session, rejects cross-origin writes and reports unconfigured LINE',async()=>{const {env}=setup();let r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/me'),env);assert.equal(r.status,401);r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/profile',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),env);assert.equal(r.status,403);r=await worker.fetch(new Request(env.APP_ORIGIN+'/api/auth/line'),env);assert.equal(r.status,503);});
test('cloud profiles validate decks, enforce transfer cooldown and count only cloud users',async()=>{const {accounts}=setup();await accounts.fetch(request('login',{id:'a',name:'A',picture:'',session:'one'}));let r=await accounts.fetch(request('profile',{id:'a',faction:'shu',decks:{shu:defaultDeck('shu')}}));assert.equal(r.status,200);r=await accounts.fetch(request('profile',{id:'a',faction:'shu',decks:{shu:['spear']}}));assert.equal(r.status,400);r=await accounts.fetch(request('world',{}));assert.equal((await r.json()).factions.shu.players,1);await accounts.fetch(request('profile',{id:'a',faction:'wei'}));r=await accounts.fetch(request('profile',{id:'a',faction:'wu'}));assert.equal(r.status,400);});
test('matched humans check membership, hides opponent hand and simulates on server',async()=>{const {env}=setup(),storage=new Storage(),ctx={storage,blockConcurrencyWhile:fn=>{ctx.ready=fn();}},m=new Match(ctx,env);await ctx.ready;const a={id:'a',name:'A',faction:'shu',decks:{shu:defaultDeck('shu')}},b={id:'b',name:'B',faction:'wei',decks:{wei:defaultDeck('wei')}},room={id:'room',host:a,guest:b,expires:Date.now()+600000};let r=await m.fetch(request('state',{room,user:a}));assert.equal((await r.json()).battle,null);await m.fetch(request('ready',{room,user:a}));assert.equal(m.battle,null);r=await m.fetch(request('ready',{room,user:b}));const d=await r.json();assert.equal(d.side,1);assert.equal(d.battle.sides[0].queue.length,0);assert.equal(d.battle.sides[1].queue.length,8);r=await m.fetch(request('state',{room,user:{id:'c'}}));assert.equal(r.status,403);await m.alarm();assert.ok(m.battle.elapsed>0);const count=m.battle.units.length;for(let i=0;i<20;i++)await m.alarm();assert.equal(m.battle.units.length,count);});

test('matchmaking pairs distinct players, keeps assignments stable and supports cancellation',async()=>{const {accounts}=setup();const a={id:'a',faction:'shu'},b={id:'b',faction:'wei'},c={id:'c',faction:'wu'};const queue=async user=>(await accounts.fetch(request('matchmaking',{user}))).json();assert.equal((await queue(a)).matched,false);assert.equal((await queue(a)).matched,false);const pair=await queue(b);assert.equal(pair.matched,true);assert.equal((await queue(a)).id,pair.id);assert.equal((await queue(b)).id,pair.id);assert.equal((await queue(c)).matched,false);assert.equal((await (await accounts.fetch(request('cancel',{user:c}))).json()).cancelled,true);assert.equal((await queue({id:'d',faction:'qun'})).matched,false);});
test('expired queue entries never become opponents',async()=>{const {accounts,storage}=setup();await storage.put('queue:old',{user:{id:'old'},expires:Date.now()-1});const d=await (await accounts.fetch(request('matchmaking',{user:{id:'new',faction:'shu'}}))).json();assert.equal(d.matched,false);assert.equal(await storage.get('queue:old'),undefined);});

test('world area derives only from server contribution and never from AI or player count',async()=>{const {accounts,storage}=setup();await storage.put('user:a',{id:'a',faction:'shu',contribution:30});await storage.put('user:b',{id:'b',faction:'wei',contribution:10});await storage.put('user:c',{id:'c',faction:'wu',contribution:0,records:[{winner:0}]});const d=await (await accounts.fetch(request('world',{}))).json();assert.deepEqual(d.territory,{shu:7500,wei:2500,wu:0,qun:0});});
