import test from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,defaultDeck,validateDeck,FACTIONS} from '../public/src/data.js';
import {Battle,walkable,findPath,advanceGround,TERRAIN,directPath} from '../public/src/engine.js';
test('32 cards and all legal faction decks',()=>{assert.equal(CARDS.length,32);for(const f of Object.keys(FACTIONS))assert.ok(validateDeck(f,defaultDeck(f)));assert.equal(validateDeck('shu',defaultDeck('wei')),false);assert.equal(validateDeck('shu',['spear','shield','archer','cavalry','fireball','arrows','lightning','fire']),false);});
test('placement validates before spending; legal play rotates hand',()=>{const b=new Battle('shu',defaultDeck('shu'));assert.equal(b.play(0,0,300,200),false);assert.equal(b.sides[0].morale,5);assert.equal(b.play(0,0,150,700),true);assert.equal(b.sides[0].morale,0);assert.equal(b.sides[0].queue.at(-1),'guanyu');assert.equal(b.play(0,0,150,700),false);});
test('ultimates one use, dead lords cannot activate',()=>{for(const f of Object.keys(FACTIONS)){const b=new Battle(f,defaultDeck(f));b.sides[0].charge=100;assert.equal(b.ultimate(0),true);assert.equal(b.ultimate(0),false);}const b=new Battle('shu',defaultDeck('shu'));b.sides[0].charge=100;b.damage(b.sides[0].lord,100000,1);assert.equal(b.ultimate(0),false);const charge=b.sides[0].charge;b.gain(0,5);assert.equal(b.sides[0].charge,charge);});
test('lord respawns after twelve seconds and grants enemy morale',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[0].lord;b.damage(u,100000,1);assert.equal(b.sides[1].morale,6);for(let i=0;i<121;i++)b.update(.1);assert.notEqual(b.sides[0].lord,u);assert.ok(b.sides[0].lord.hp>0);});
test('lightning telegraph and lord spell reduction',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[1].lord;u.speed=0;b.cast(CARDS.find(c=>c.id==='lightning'),0,u.x,u.y);b.aiTimer=100;for(let i=0;i<7;i++)b.update(.1);assert.equal(u.hp,u.maxHp);for(let i=0;i<2;i++)b.update(.1);assert.ok(u.hp<u.maxHp);assert.ok(u.maxHp-u.hp<620);});
test('all faction pairings finish and stay finite',()=>{for(const f of Object.keys(FACTIONS))for(const e of Object.keys(FACTIONS)){let seed=27;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const b=new Battle(f,defaultDeck(f),e,random);for(let i=0;i<1810&&!b.result;i++){if(i%10===0){const choices=b.hand(0).map((c,j)=>({c,j})).filter(o=>o.c.cost<=b.sides[0].morale);if(choices.length){const o=choices[0];b.play(0,o.j,150,o.c.type==='spell'?250:650);}b.ultimate(0);}b.update(.1);assert.ok(b.units.every(u=>Number.isFinite(u.hp)&&walkable(u)));}assert.ok(b.result,`${f}/${e} must finish`);assert.ok([-1,0,1].includes(b.result.winner));}});

test('bridge routing chooses nearest crossing and never walks through water',()=>{for(const x of [60,150,300,450,540]){const unit={x,y:750};const goal={x,y:250};const route=findPath(unit,goal);assert.ok(route.length);for(let i=0;i<700&&Math.hypot(unit.x-goal.x,unit.y-goal.y)>1;i++){advanceGround(unit,goal,3);assert.ok(walkable(unit),JSON.stringify(unit));}assert.ok(Math.hypot(unit.x-goal.x,unit.y-goal.y)<1);}const left=findPath({x:60,y:700},{x:70,y:250});assert.ok(left.some(p=>p.x===150));const right=findPath({x:540,y:700},{x:530,y:250});assert.ok(right.some(p=>p.x===450));assert.equal(directPath({x:300,y:700},{x:300,y:250}),false);});
test('lords, fear and knockback remain on land; river deploy rejected without spend',()=>{const b=new Battle('shu',defaultDeck('shu'));const morale=b.sides[0].morale;assert.equal(b.play(0,0,300,500),false);assert.equal(b.sides[0].morale,morale);b.moveLord(0,300,500);assert.ok(walkable(b.sides[0].lord.destination));b.moveLord(0,300,250);b.aiTimer=1000;for(let i=0;i<200;i++){b.update(.1);assert.ok(b.units.every(walkable));}const u=b.sides[0].lord;u.fearUntil=b.elapsed+2;for(let i=0;i<20;i++){b.update(.1);assert.ok(walkable(u));}});
test('ambush never spawns units in water',()=>{const b=new Battle('shu',defaultDeck('shu'));b.cast(CARDS.find(c=>c.id==='ambush'),0,300,500);assert.ok(b.units.every(walkable));});
