import test from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,defaultDeck,validateDeck,FACTIONS} from '../public/src/data.js';
import {Battle,walkable,findPath,advanceGround,TERRAIN,directPath} from '../public/src/engine.js';
test('32 cards and all legal faction decks',()=>{assert.equal(CARDS.length,32);for(const f of Object.keys(FACTIONS))assert.ok(validateDeck(f,defaultDeck(f)));assert.equal(validateDeck('shu',defaultDeck('wei')),false);assert.equal(validateDeck('shu',['spear','shield','archer','cavalry','fireball','arrows','lightning','fire']),false);});
test('placement validates before spending; legal play rotates hand',()=>{const b=new Battle('shu',defaultDeck('shu'));assert.equal(b.play(0,0,300,200),false);assert.equal(b.sides[0].morale,5);assert.equal(b.play(0,0,150,700),true);assert.equal(b.sides[0].morale,0);assert.equal(b.sides[0].queue.at(-1),'guanyu');assert.equal(b.play(0,0,150,700),false);});
test('ultimates one use, dead lords cannot activate',()=>{for(const f of Object.keys(FACTIONS)){const b=new Battle(f,defaultDeck(f));b.sides[0].charge=100;assert.equal(b.ultimate(0),true);assert.equal(b.ultimate(0),false);}const b=new Battle('shu',defaultDeck('shu'));b.sides[0].charge=100;b.damage(b.sides[0].lord,100000,1);assert.equal(b.ultimate(0),false);const charge=b.sides[0].charge;b.gain(0,5);assert.equal(b.sides[0].charge,charge);});
test('lord respawns after twelve seconds and grants enemy morale',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[0].lord;b.damage(u,100000,1);assert.equal(b.sides[1].morale,6);for(let i=0;i<121;i++)b.update(.1);assert.notEqual(b.sides[0].lord,u);assert.ok(b.sides[0].lord.hp>0);});
test('lightning telegraph and lord spell reduction',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[1].lord;u.speed=0;b.cast(CARDS.find(c=>c.id==='lightning'),0,u.x,u.y);b.aiTimer=100;for(let i=0;i<7;i++)b.update(.1);assert.equal(u.hp,u.maxHp);for(let i=0;i<2;i++)b.update(.1);assert.ok(u.hp<u.maxHp);assert.ok(u.maxHp-u.hp<620);});
test('all faction pairings finish and stay finite',()=>{for(const f of Object.keys(FACTIONS))for(const e of Object.keys(FACTIONS)){let seed=27;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const b=new Battle(f,defaultDeck(f),e,random);for(let i=0;i<1810&&!b.result;i++){if(i%10===0){const choices=b.hand(0).map((c,j)=>({c,j})).filter(o=>o.c.cost<=b.sides[0].morale);if(choices.length){const o=choices[0];b.play(0,o.j,150,o.c.type==='spell'?250:650);}b.ultimate(0);}b.update(.1);assert.ok(b.units.every(u=>Number.isFinite(u.hp)&&walkable(u)));}assert.ok(b.result,`${f}/${e} must finish`);assert.ok([-1,0,1].includes(b.result.winner));}});

test('bridge routing chooses nearest crossing and never walks through water',()=>{for(const x of [60,150,300,450,540]){const unit={x,y:750};const goal={x,y:250};const route=findPath(unit,goal);assert.ok(route.length);for(let i=0;i<700&&Math.hypot(unit.x-goal.x,unit.y-goal.y)>1;i++){advanceGround(unit,goal,3);assert.ok(walkable(unit),JSON.stringify(unit));}assert.ok(Math.hypot(unit.x-goal.x,unit.y-goal.y)<1);}const left=findPath({x:60,y:700},{x:70,y:250});assert.ok(left.some(p=>p.x===149));const right=findPath({x:540,y:700},{x:530,y:250});assert.ok(right.some(p=>p.x===454));assert.equal(directPath({x:300,y:700},{x:300,y:250}),false);});
test('lords, fear and knockback remain on land; river deploy rejected without spend',()=>{const b=new Battle('shu',defaultDeck('shu'));const morale=b.sides[0].morale;assert.equal(b.play(0,0,300,450),false);assert.equal(b.sides[0].morale,morale);b.moveLord(0,300,450);assert.ok(walkable(b.sides[0].lord.destination));b.moveLord(0,300,250);b.aiTimer=1000;for(let i=0;i<200;i++){b.update(.1);assert.ok(b.units.every(walkable));}const u=b.sides[0].lord;u.fearUntil=b.elapsed+2;for(let i=0;i<20;i++){b.update(.1);assert.ok(walkable(u));}});
test('ambush never spawns units in water',()=>{const b=new Battle('shu',defaultDeck('shu'));b.cast(CARDS.find(c=>c.id==='ambush'),0,300,450);assert.ok(b.units.every(walkable));});

test('art-aligned bases stay inside battlefield and decorative card panel is not deployable',()=>{const b=new Battle('shu',defaultDeck('shu'));assert.ok(b.buildings.every(walkable));assert.equal(b.buildings.find(u=>u.castle&&u.side===0).y,723);assert.equal(b.play(0,0,300,950),false);b.moveLord(0,300,950);assert.equal(b.sides[0].lord.destination.y,TERRAIN.maxY);});

test('ranged attacks emit visual projectiles without extra damage and record reactions',()=>{for(const id of ['archer','catapult','zhugeliang']){const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];b.spawn({...CARDS.find(c=>c.id===id),count:1},0,150,600);b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,150,550);const u=b.units[0],target=b.units.find(t=>t.side===1);u.cool=0;u.range=220;u.count=1;const hp=target.hp;b.update(.1);assert.equal(u.attackAt,b.elapsed);assert.ok(Number.isFinite(u.attackDirection.x));assert.equal(target.hurtAt,b.elapsed);assert.ok(target.hp<hp);const e=b.effects.find(e=>e.id==='projectile');assert.ok(e);assert.equal(e.kind,id==='catapult'?'stone':id==='zhugeliang'?'magic':'arrow');const after=target.hp;u.cool=10;for(const t of b.units)t.atk=0;for(let i=0;i<5;i++)b.update(.1);assert.equal(target.hp,after);assert.equal(b.effects.some(e=>e.id==='projectile'),false);}});

test('deployment previews share validation without spending or rotating cards',()=>{const b=new Battle('shu',defaultDeck('shu')),queue=[...b.sides[0].queue],morale=b.sides[0].morale;assert.equal(b.canPlay(0,0,150,700),true);assert.equal(b.canPlay(0,0,300,450),false);assert.equal(b.canPlay(0,0,300,950),false);assert.equal(b.canPlay(0,0,NaN,650),false);assert.equal(b.sides[0].morale,morale);assert.deepEqual(b.sides[0].queue,queue);assert.equal(b.play(0,0,150,700),true);assert.equal(b.canPlay(0,0,150,700),false);});
test('friendly separation stays on land and respects per-unit displacement budget',()=>{for(const y of [400,450,500]){const b=new Battle('shu',defaultDeck('shu'));b.spawn({...CARDS.find(c=>c.id==='spear'),count:1},0,149,y);b.spawn({...CARDS.find(c=>c.id==='spear'),count:1},0,149,y);const units=b.units.filter(u=>!u.lord),before=units.map(u=>({x:u.x,y:u.y})),lord={x:b.sides[0].lord.x,y:b.sides[0].lord.y};for(let i=0;i<20;i++)b.separateUnits(.1);assert.ok(units.every(walkable));for(let i=0;i<units.length;i++)assert.ok(Math.hypot(units[i].x-before[i].x,units[i].y-before[i].y)<=16.00001);assert.deepEqual({x:b.sides[0].lord.x,y:b.sides[0].lord.y},lord);assert.ok(Math.hypot(units[0].x-units[1].x,units[0].y-units[1].y)>0);}});

test('AI retreats a wounded lord and avoids spells against isolated enemies',()=>{const b=new Battle('shu',defaultDeck('shu'));const p=b.sides[1];p.lord.hp=p.lord.maxHp*.2;p.morale=10;p.queue=['fireball','arrows','lightning','fire','spear','shield','cavalry','medic'];b.units=b.units.filter(u=>u.lord);b.ai();assert.equal(p.lord.destination.y,100);assert.equal(p.morale,10);assert.equal(b.effects.some(e=>['fireball','arrows','lightning','fire'].includes(e.id)),false);});
