import test from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,defaultDeck,trialDeck,validateDeck,FACTIONS} from '../public/src/data.js';
import {Battle,trialDifficulty,walkable,findPath,advanceGround,TERRAIN,directPath,smoothTrialDifficulty,placementPoint,CARD_PANEL_TOP} from '../public/src/engine.js';
test('32 cards and all legal faction decks',()=>{assert.equal(CARDS.length,32);for(const f of Object.keys(FACTIONS))assert.ok(validateDeck(f,defaultDeck(f)));assert.equal(validateDeck('shu',defaultDeck('wei')),false);assert.equal(validateDeck('shu',['spear','shield','archer','cavalry','fireball','arrows','lightning','fire']),false);});
test('placement validates before spending; legal play rotates hand',()=>{const b=new Battle('shu',defaultDeck('shu'));assert.equal(b.play(0,0,NaN,200),false);assert.equal(b.sides[0].morale,5);assert.equal(b.play(0,0,150,700),true);assert.equal(b.sides[0].morale,0);assert.equal(b.sides[0].queue.at(-1),'guanyu');assert.equal(b.play(0,0,150,700),false);});
test('ultimates one use, dead lords cannot activate',()=>{for(const f of Object.keys(FACTIONS)){const b=new Battle(f,defaultDeck(f));b.sides[0].charge=100;assert.equal(b.ultimate(0),true);assert.equal(b.ultimate(0),false);}const b=new Battle('shu',defaultDeck('shu'));b.sides[0].charge=100;b.damage(b.sides[0].lord,100000,1);assert.equal(b.ultimate(0),false);const charge=b.sides[0].charge;b.gain(0,5);assert.equal(b.sides[0].charge,charge);});
test('lord respawns after twelve seconds and grants enemy morale',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[0].lord;b.damage(u,100000,1);assert.equal(b.sides[1].morale,6);for(let i=0;i<121;i++)b.update(.1);assert.notEqual(b.sides[0].lord,u);assert.ok(b.sides[0].lord.hp>0);});
test('lightning telegraph and lord spell reduction',()=>{const b=new Battle('shu',defaultDeck('shu'));const u=b.sides[1].lord;u.speed=0;b.cast(CARDS.find(c=>c.id==='lightning'),0,u.x,u.y);b.aiTimer=100;for(let i=0;i<7;i++)b.update(.1);assert.equal(u.hp,u.maxHp);for(let i=0;i<2;i++)b.update(.1);assert.ok(u.hp<u.maxHp);assert.ok(u.maxHp-u.hp<620);});
test('all faction pairings finish and stay finite',()=>{for(const f of Object.keys(FACTIONS))for(const e of Object.keys(FACTIONS)){let seed=27;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const b=new Battle(f,defaultDeck(f),e,random);for(let i=0;i<2210&&!b.result;i++){if(i%10===0){const choices=b.hand(0).map((c,j)=>({c,j})).filter(o=>o.c.cost<=b.sides[0].morale);if(choices.length){const o=choices[0];b.play(0,o.j,150,o.c.type==='spell'?250:650);}b.ultimate(0);}b.update(.1);assert.ok(b.units.every(u=>Number.isFinite(u.hp)&&walkable(u)));}assert.ok(b.result,`${f}/${e} must finish`);assert.ok([-1,0,1].includes(b.result.winner));}});

test('bridge routing chooses nearest crossing and never walks through water',()=>{for(const x of [60,150,300,450,540]){const unit={x,y:750};const goal={x,y:250};const route=findPath(unit,goal);assert.ok(route.length);for(let i=0;i<700&&Math.hypot(unit.x-goal.x,unit.y-goal.y)>1;i++){advanceGround(unit,goal,3);assert.ok(walkable(unit),JSON.stringify(unit));}assert.ok(Math.hypot(unit.x-goal.x,unit.y-goal.y)<1);}const left=findPath({x:60,y:700},{x:70,y:250});assert.ok(left.some(p=>p.x===149));const right=findPath({x:540,y:700},{x:530,y:250});assert.ok(right.some(p=>p.x===454));assert.equal(directPath({x:300,y:700},{x:300,y:250}),false);});
test('lords, fear and knockback remain on land; river deploy snaps to own bank',()=>{const b=new Battle('shu',defaultDeck('shu'));const morale=b.sides[0].morale;assert.equal(b.play(0,0,300,450),true);assert.equal(b.units.at(-1).y,490);assert.equal(b.sides[0].morale,morale-5);b.moveLord(0,300,450);assert.ok(walkable(b.sides[0].lord.destination));b.moveLord(0,300,250);b.aiTimer=1000;for(let i=0;i<200;i++){b.update(.1);assert.ok(b.units.every(walkable));}const u=b.sides[0].lord;u.fearUntil=b.elapsed+2;for(let i=0;i<20;i++){b.update(.1);assert.ok(walkable(u));}});
test('ambush never spawns units in water',()=>{const b=new Battle('shu',defaultDeck('shu'));b.cast(CARDS.find(c=>c.id==='ambush'),0,300,450);assert.ok(b.units.every(walkable));});

test('art-aligned bases stay inside battlefield and panel releases snap to the battlefield edge',()=>{const b=new Battle('shu',defaultDeck('shu'));assert.ok(b.buildings.every(walkable));assert.equal(b.buildings.find(u=>u.castle&&u.side===0).y,723);assert.equal(b.play(0,0,300,950),true);assert.equal(b.units.at(-1).y,762);b.moveLord(0,300,950);assert.equal(b.sides[0].lord.destination.y,TERRAIN.maxY);});

test('projectiles deal damage once on impact and pause with combat',()=>{for(const id of ['archer','catapult','zhugeliang']){const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];b.spawn({...CARDS.find(c=>c.id===id),count:1},0,150,600);b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,150,550);const u=b.units[0],target=b.units[1];u.cool=0;u.range=220;target.speed=0;target.atk=0;const hp=target.hp;b.update(.1);assert.equal(u.attackAt,b.elapsed);assert.equal(target.hp,hp);assert.ok(b.effects.some(e=>e.id==='projectile'));u.cool=10;b.pauseRemaining=1;for(let i=0;i<10;i++)b.update(.1);assert.equal(target.hp,hp);for(let i=0;i<5;i++)b.update(.1);assert.ok(target.hp<hp);const after=target.hp;for(let i=0;i<10;i++)b.update(.1);assert.equal(target.hp,after);assert.equal(b.effects.some(e=>e.id==='projectile'),false);}});


test('deployment previews share validation without spending or rotating cards',()=>{const b=new Battle('shu',defaultDeck('shu')),queue=[...b.sides[0].queue],morale=b.sides[0].morale;assert.equal(b.canPlay(0,0,150,700),true);assert.equal(b.canPlay(0,0,300,450),true);assert.equal(b.canPlay(0,0,300,950),true);assert.equal(b.canPlay(0,0,NaN,650),false);assert.equal(b.sides[0].morale,morale);assert.deepEqual(b.sides[0].queue,queue);assert.equal(b.play(0,0,150,700),true);assert.equal(b.canPlay(0,0,150,700),false);});
test('friendly separation stays on land and respects per-unit displacement budget',()=>{for(const y of [400,450,500]){const b=new Battle('shu',defaultDeck('shu'));b.spawn({...CARDS.find(c=>c.id==='spear'),count:1},0,149,y);b.spawn({...CARDS.find(c=>c.id==='spear'),count:1},0,149,y);const units=b.units.filter(u=>!u.lord),before=units.map(u=>({x:u.x,y:u.y})),lord={x:b.sides[0].lord.x,y:b.sides[0].lord.y};for(let i=0;i<20;i++)b.separateUnits(.1);assert.ok(units.every(walkable));for(let i=0;i<units.length;i++)assert.ok(Math.hypot(units[i].x-before[i].x,units[i].y-before[i].y)<=16.00001);assert.deepEqual({x:b.sides[0].lord.x,y:b.sides[0].lord.y},lord);assert.ok(Math.hypot(units[0].x-units[1].x,units[0].y-units[1].y)>0);}});

test('AI retreats a wounded lord and avoids spells against isolated enemies',()=>{const b=new Battle('shu',defaultDeck('shu'));const p=b.sides[1];p.lord.hp=p.lord.maxHp*.2;p.morale=10;p.queue=['fireball','arrows','lightning','fire','spear','shield','cavalry','medic'];b.units=b.units.filter(u=>u.lord);b.ai();assert.equal(p.lord.destination.y,100);assert.equal(p.morale,10);assert.equal(b.effects.some(e=>['fireball','arrows','lightning','fire'].includes(e.id)),false);});

test('AI cycles a stalled spell-only hand and advances a supported healthy lord',()=>{const b=new Battle('shu',defaultDeck('shu'));const p=b.sides[1];p.morale=10;p.queue=['fireball','arrows','lightning','fire','spear','shield','cavalry','medic'];b.elapsed=7;b.ai();assert.ok(p.morale<10);assert.equal(p.lastAiPlay,7);assert.ok(p.queue.slice(0,4).includes('spear'));const c=new Battle('shu',defaultDeck('shu'));c.spawn({...CARDS.find(x=>x.id==='spear'),count:3},1,149,350);c.ai();assert.ok(c.sides[1].lord.destination.x<300);assert.ok(c.sides[1].lord.destination.y>=300);});

test('ultimate pauses combat and input for two seconds then resumes',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.sides[0].charge=100;assert.equal(b.ultimate(0),true);const time=b.time,elapsed=b.elapsed,morale=b.sides[0].morale,positions=b.units.map(u=>[u.x,u.y]),hp=b.units.map(u=>u.hp);assert.equal(b.cinematic.faction,'shu');assert.equal(b.play(0,0,150,700),false);b.moveLord(0,150,700);assert.equal(b.sides[0].lord.destination,undefined);for(let i=0;i<20;i++)b.update(.1);assert.equal(b.time,time);assert.equal(b.elapsed,elapsed);assert.equal(b.sides[0].morale,morale);assert.deepEqual(b.units.map(u=>[u.x,u.y]),positions);assert.deepEqual(b.units.map(u=>u.hp),hp);assert.equal(b.pauseRemaining,0);b.update(.1);assert.ok(b.time<time);assert.ok(b.elapsed>elapsed);});

test('trial difficulty rises with recent win rate, eases after losses and limits small samples',()=>{const results=(wins,total)=>Array.from({length:total},(_,i)=>({winner:i<wins?0:1}));assert.equal(trialDifficulty([]),0);assert.equal(trialDifficulty(results(0,20)),0);assert.equal(trialDifficulty(results(8,20)),0);assert.ok(trialDifficulty(results(12,20))>trialDifficulty(results(9,20)));assert.equal(trialDifficulty(results(20,20)),1);assert.equal(trialDifficulty(results(1,1)),.2);assert.equal(trialDifficulty([...results(20,20),...results(0,20)]),0);assert.equal(trialDifficulty([{winner:-1},{winner:99}]),0);});
test('trial difficulty improves tactics and decision cadence without changing unit strength or speed',()=>{const easy=new Battle('shu',defaultDeck('shu'),'wei',()=>.99,0),hard=new Battle('shu',defaultDeck('shu'),'wei',()=>.99,1);assert.deepEqual(easy.units,hard.units);assert.deepEqual(easy.buildings,hard.buildings);assert.ok(easy.aiTimer>hard.aiTimer);for(const b of [easy,hard]){b.spawn({...CARDS.find(c=>c.id==='spear'),count:3},1,149,350);b.ai();}assert.equal(easy.sides[1].lord.destination.x,300);assert.ok(hard.sides[1].lord.destination.x<300);assert.ok(hard.sides[1].lord.destination.y>easy.sides[1].lord.destination.y);});

test('adaptive beginner and middle trials finish with finite, walkable units',()=>{for(const difficulty of [0,.5]){let seed=41;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296),b=new Battle('shu',defaultDeck('shu'),'wu',random,difficulty);for(let i=0;i<2210&&!b.result;i++){if(i%15===0){for(let index=0;index<4;index++)if(b.play(0,index,149,650))break;b.ultimate(0);}b.update(.1);assert.ok(b.units.every(u=>Number.isFinite(u.hp)&&walkable(u)));}assert.ok(b.result);}});

test('idle lords hold position without enemies and never attack buildings',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;const u=b.sides[0].lord;assert.equal(u.y,651);u.x=149;u.y=550;b.units=[u];const towers=b.buildings.filter(t=>t.side===1);const hp=towers.map(t=>t.hp);for(let i=0;i<180;i++)b.update(.1);assert.deepEqual({x:u.x,y:u.y},{x:149,y:550});assert.deepEqual(towers.map(t=>t.hp),hp);b.moveLord(0,149,212);for(let i=0;i<200;i++)b.update(.1);assert.deepEqual(towers.map(t=>t.hp),hp);});
test('lord follows manual order, attacks nearby units and then holds position',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;const u=b.sides[0].lord;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,300,640);const enemy=b.units.at(-1);enemy.speed=0;enemy.atk=0;const hp=enemy.hp;b.update(.1);assert.ok(enemy.hp<hp);assert.equal(u.y,651);b.moveLord(0,149,600);const order={...u.destination};u.cool=0;b.update(.1);assert.ok(enemy.hp<hp);assert.deepEqual(u.destination,order);enemy.hp=0;for(let i=0;i<45;i++)b.update(.1);assert.ok(u.x<200);assert.ok(walkable(u));const stopped={x:u.x,y:u.y};for(let i=0;i<60;i++)b.update(.1);assert.deepEqual({x:u.x,y:u.y},stopped);assert.ok(Math.hypot(u.x-149,u.y-600)<5);});

test('mirrored deployment, bases and paths use symmetrical playable bounds',()=>{const b=new Battle('shu',defaultDeck('shu'),'shu');for(let y=100;y<=762;y+=7)for(const x of [50,149,300,454,550])assert.equal(b.canPlay(0,0,x,y),b.canPlay(1,0,x,862-y),`${x},${y}`);for(const a of b.buildings.filter(b=>b.side===0)){const other=b.buildings.find(b=>b.side===1&&b.castle===a.castle&&b.tower===a.tower&&b.x===a.x);assert.ok(other);assert.equal(a.y+other.y,862);}assert.equal(TERRAIN.minY+TERRAIN.maxY,862);assert.equal(TERRAIN.riverTop+TERRAIN.riverBottom,862);});
test('difficulty adjusts at most one tenth per completed trial and decks remain legal',()=>{for(const f of Object.keys(FACTIONS))for(const style of ['rush','defense','siege'])assert.ok(validateDeck(f,trialDeck(f,style)));assert.equal(smoothTrialDifficulty(Array.from({length:20},()=>({winner:0})),0),.1);assert.ok(Math.abs(smoothTrialDifficulty(Array.from({length:20},()=>({winner:1})),.8)-.7)<1e-9);});
test('medics follow and heal injured allies even without enemy targets',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},0,149,550);b.spawn({...CARDS.find(c=>c.id==='medic'),count:1},0,149,740);const ally=b.units[0],medic=b.units[1];ally.hp=100;ally.speed=0;for(let i=0;i<80;i++)b.update(.1);assert.ok(medic.y<700);assert.ok(ally.hp>100);assert.ok(walkable(medic));});
test('charge needs sustained movement, consumes one bonus and keeps movement speed',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];b.spawn({...CARDS.find(c=>c.id==='cavalry'),count:1},0,149,700);b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,149,550);const rider=b.units[0],target=b.units[1];target.speed=0;target.atk=0;const hp=target.hp;for(let i=0;i<30&&!target.hurtAt;i++)b.update(.1);assert.ok(target.hp<hp-65*(1-target.def));assert.equal(rider.speed,56);assert.ok(rider.nextChargeAt>b.elapsed);assert.equal(rider.chargeReady,false);});

test('malformed decks and inherited faction names are rejected',()=>{for(const deck of [undefined,null,'12345678',{},['spear']])assert.equal(validateDeck('shu',deck),false);for(const f of ['__proto__','constructor','bad'])assert.equal(validateDeck(f,defaultDeck('shu')),false);});
test('lords stay on their own bank under manual orders, fear and knockback on both sides',()=>{for(const f of Object.keys(FACTIONS)){const b=new Battle(f,defaultDeck(f));b.aiTimer=1000;b.buildings=[];for(const side of [0,1]){const u=b.sides[side].lord;assert.equal(b.moveLord(side,149,side?700:150),true);assert.equal(u.destination.y,side?372:490);for(let i=0;i<100;i++)b.update(.1);assert.ok(side?u.y<=372:u.y>=490);advanceGround(u,{x:149,y:side?700:150},1000);assert.ok(side?u.y<=372:u.y>=490);u.fearUntil=b.elapsed+1;b.update(.1);assert.ok(side?u.y<=372:u.y>=490);assert.ok(walkable(u));}}});
test('lords chase invaders, fight during manual orders and resume movement when clear',()=>{const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.buildings=[];const u=b.sides[0].lord;b.units=[u];b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,400,550);const near=b.units.at(-1);b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},1,100,500);const far=b.units.at(-1);for(const t of [near,far]){t.speed=0;t.atk=0;}b.update(.1);assert.ok(u.x>300);assert.ok(u.y<651);near.x=u.x+20;near.y=u.y;const hp=near.hp;u.cool=0;b.update(.1);assert.ok(near.hp<hp);assert.equal(far.hp,far.maxHp);const retreatHp=near.hp;assert.equal(b.moveLord(0,100,700),true);u.cool=0;const startX=u.x;b.update(.1);assert.equal(u.x,startX);assert.ok(near.hp<retreatHp);assert.ok(u.destination);b.units=[u];for(let i=0;i<180;i++)b.update(.1);assert.ok(Math.hypot(u.x-100,u.y-700)<5);});

test('medics prioritize absolute remaining HP and cap healing at maximum HP',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];const y=side?300:600;for(const x of [100,150])b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},side,x,y);b.spawn({...CARDS.find(c=>c.id==='medic'),count:1},side,125,y+(side?-55:55));const [low,ratio,medic]=b.units;low.hp=200;low.maxHp=250;ratio.hp=300;ratio.maxHp=2000;low.speed=ratio.speed=0;medic.cool=0;b.update(.1);assert.equal(low.hp,250);assert.equal(ratio.hp,300);b.update(.1);assert.equal(ratio.hp,300);medic.cool=0;b.update(.1);assert.equal(ratio.hp,365);}});
test('uninjured formations and lone medics advance on both sides using bridges',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'));b.aiTimer=1000;b.units=[];b.buildings=[];b.spawn({...CARDS.find(c=>c.id==='shield'),count:1},side,149,side?350:512);b.spawn({...CARDS.find(c=>c.id==='medic'),count:1},side,149,side?150:712);const ally=b.units[0],medic=b.units[1];ally.speed=0;const start=medic.y;for(let i=0;i<40;i++)b.update(.1);assert.ok(side?medic.y>start:medic.y<start);b.units=[medic];medic.x=300;medic.y=side?300:562;for(let i=0;i<200;i++){b.update(.1);assert.ok(walkable(medic));}assert.ok(side?medic.y>TERRAIN.riverBottom:medic.y<TERRAIN.riverTop);}});

test('outer edge releases snap to the closest wall for both players',()=>{for(const side of [0,1])for(const [x,y,expected]of [[-8,side?200:620,{x:50,y:side?200:620}],[608,side?200:620,{x:550,y:side?200:620}],[300,side?40:800,{x:300,y:side?100:762}]]){const b=new Battle('shu',defaultDeck('shu'));b.sides[side].queue=defaultDeck('shu');b.sides[side].morale=10;const before=b.sides[side].morale;assert.deepEqual(placementPoint(x,y,side),expected);assert.equal(b.canPlay(side,0,x,y),true);assert.equal(b.play(side,0,x,y),true);const unit=b.units.at(-1);assert.equal(unit.x,expected.x);assert.equal(unit.y,expected.y);assert.equal(b.sides[side].morale,before-5);assert.ok(walkable(unit));}});
test('lords attack an enemy encountered during a manual route, retain the destination and resume after the enemy dies',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'),'shu');b.ai=()=>{};b.buildings=[];const u=b.sides[side].lord;b.units=[u];const y=side?200:650;u.x=100;u.y=y;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1,speed:0,atk:0,hp:10000},1-side,220,y);const enemy=b.units.at(-1);b.moveLord(side,500,y);const destination={...u.destination};let attacked=false;for(let i=0;i<100;i++){const before=enemy.hp;b.update(.1);if(enemy.hp<before){attacked=true;assert.deepEqual(u.destination,destination);const position={x:u.x,y:u.y};b.update(.1);assert.deepEqual({x:u.x,y:u.y},position);break;}}assert.equal(attacked,true);enemy.hp=0;const x=u.x;b.update(.1);assert.ok(u.x>x);assert.deepEqual(u.destination,destination);}});
test('lords only seek units inside their own territory even when an opposing-bank enemy is in range',()=>{for(const side of [0,1]){const b=new Battle('wei',defaultDeck('wei'),'wei');b.ai=()=>{};b.buildings=[];const u=b.sides[side].lord;b.units=[u];u.x=149;u.y=side?372:490;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1,speed:0,atk:0},1-side,149,side?490:372);const enemy=b.units.at(-1),hp=enemy.hp;u.cool=0;b.update(.1);assert.equal(enemy.hp,hp);assert.equal(b.effects.some(e=>e.id==='projectile'&&e.side===side),false);}});
test('healthy allies do not hold medics back; medics heal on the route then resume toward the enemy castle',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'));b.ai=()=>{};b.buildings=[];b.units=[];const y=side?300:562;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1,speed:0},side,149,y);b.spawn({...CARDS.find(c=>c.id==='medic'),count:1},side,149,y);const [ally,medic]=b.units;medic.cool=0;ally.hp=ally.maxHp-10;const start=medic.y;b.update(.1);assert.equal(ally.hp,ally.maxHp);assert.equal(medic.y,start);for(let i=0;i<500;i++)b.update(.1);assert.ok(Math.hypot(medic.x-300,medic.y-(side?723:139))<9);assert.ok(walkable(medic));}});

test('lords stop where combat ends on both sides',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'),'shu');b.ai=()=>{};b.buildings=[];const u=b.sides[side].lord;b.units=[u];u.x=100;u.y=side?200:650;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1,speed:0,atk:0},1-side,300,u.y);const enemy=b.units.at(-1);b.update(.1);assert.ok(u.x>100);enemy.x=u.x+20;u.cool=0;b.update(.1);assert.ok(enemy.hp<enemy.maxHp);enemy.hp=0;const position={x:u.x,y:u.y};for(let i=0;i<50;i++)b.update(.1);assert.deepEqual({x:u.x,y:u.y},position);}});

test('every finite troop release snaps to the closest own-land rectangle on both sides',()=>{for(const side of [0,1])for(const [x,y] of [[-999,-999],[999,999],[300,431],[300,side?700:200],[149,430]]){const b=new Battle('shu',defaultDeck('shu'),'shu');b.sides[side].morale=10;const c=b.hand(side)[0],point=placementPoint(x,y,side,c);assert.ok(walkable(point));assert.ok(side?point.y<=372:point.y>=490);assert.equal(b.play(side,0,x,y),true);const unit=b.units.at(-1);assert.equal(unit.x,point.x);assert.equal(unit.y,point.y);assert.equal(b.sides[side].morale,10-c.cost);}for(const id of ['ambush','barricade']){const p=placementPoint(160,431,0,CARDS.find(c=>c.id===id));assert.ok(walkable(p));assert.equal(p.x,160);}});

test('attackers retain living targets when closer enemies arrive and reacquire after death',()=>{for(const kind of ['lord','spear','ram','tower']){const b=new Battle('shu',defaultDeck('shu'));b.ai=()=>{};const lord=b.sides[0].lord,tower=b.buildings.find(t=>t.side===0&&t.tower);b.units=[];b.buildings=[];let u;if(kind==='lord'){u=lord;b.units=[u];}else if(kind==='tower'){u=tower;b.buildings=[u];}else{b.spawn({...CARDS.find(c=>c.id===kind),count:1},0,149,600);u=b.units[0];}u.x=149;u.y=600;u.speed=0;u.atk=0;const target={id:++b.id,side:1,x:149,y:550,hp:10000,maxHp:10000,atk:0,speed:0,range:0,cool:100,castle:kind==='ram'};b.buildings.push(target);b.update(.1);if(kind==='lord'){target.castle=false;b.units.push(target);b.buildings=b.buildings.filter(t=>t!==target);b.update(.1);}assert.equal(u.targetId,target.id);const nearer={...target,id:++b.id,y:590};b.units.push(nearer);b.update(.1);assert.equal(u.targetId,target.id);target.y=500;b.update(.1);assert.equal(u.targetId,target.id);target.hp=0;b.update(.1);assert.equal(u.targetId,nearer.id);}});

test('medics keep advancing during healing cooldown and after allies recover',()=>{for(const side of [0,1]){const b=new Battle('shu',defaultDeck('shu'));b.ai=()=>{};b.units=[];b.buildings=[];const y=side?300:562;b.spawn({...CARDS.find(c=>c.id==='shield'),count:1,speed:0,atk:0},side,149,y);b.spawn({...CARDS.find(c=>c.id==='medic'),count:1},side,149,y);const [ally,medic]=b.units;ally.hp-=200;medic.cool=.8;const before=medic.y;b.update(.1);assert.ok(side?medic.y>before:medic.y<before);medic.cool=0;const hp=ally.hp;b.update(.1);assert.equal(ally.hp,hp+65);ally.hp=ally.maxHp;const healedY=medic.y;b.update(.1);assert.ok(side?medic.y>healedY:medic.y<healedY);}});
