import test from 'node:test';
import assert from 'node:assert/strict';
import {EQUIPMENT,equipmentDrop,equipmentBonuses,normalizeEquipment,equipEquipment} from '../public/src/equipment.js';
import {Battle} from '../public/src/engine.js';
import {FACTIONS,defaultDeck,card} from '../public/src/data.js';
test('equipment definitions and normalization bound bonuses and discard unowned slots',()=>{assert.equal(EQUIPMENT.length,12);assert.deepEqual(equipmentBonuses({inventory:{'weapon-2':100},equipped:{weapon:'weapon-2',armor:'weapon-2'}}),{atk:.06,hp:0,charge:0,speed:0});assert.deepEqual(normalizeEquipment({inventory:{'armor-2':-1,unknown:5},equipped:{armor:'armor-2'}}).inventory,{});});
test('drops reject idle, nonhuman, abnormal and too-short results without consuming randomness',()=>{const m={players:[{id:'a'},{id:'b'}],result:{winner:0,reason:'battle',duration:40},events:[{side:0,type:'play'},{side:1,type:'move'}]};for(const invalid of [{...m,events:[]},{...m,players:[{id:'a'},{id:'a'}]},{...m,result:{...m.result,duration:19}},{...m,result:{...m.result,reason:'disconnect'}}])assert.equal(equipmentDrop(invalid,0,()=>{throw Error('unexpected RNG');}).eligible,false);assert.equal(equipmentDrop(m,3).eligible,false);assert.deepEqual(equipmentDrop(m,0,()=>0).items,['weapon-2','weapon-2']);assert.deepEqual(equipmentDrop(m,0,()=>.999).items,['mount-0','mount-0']);});
test('equipped bonuses apply only to the lord and survive respawn without stacking',()=>{const b=new Battle('shu',defaultDeck('shu'));b.ai=()=>{};const e={inventory:{'weapon-2':2,'armor-2':1,'mount-2':1,'charm-2':1},equipped:{weapon:'weapon-2',armor:'armor-2',mount:'mount-2',charm:'charm-2'}};assert.equal(b.setEquipment(0,e),true);assert.equal(b.setEquipment(0,e),true);let u=b.sides[0].lord;assert.equal(u.maxHp,FACTIONS.shu.hp*1.06);assert.equal(u.atk,FACTIONS.shu.atk*1.06);assert.equal(u.speed,FACTIONS.shu.speed*1.06);assert.equal(b.buildings[0].maxHp,1800);b.gain(0,10);assert.equal(b.sides[0].charge,10*1.05*1.06);b.damage(u,1e9,1);for(let i=0;i<121;i++)b.update(.1);u=b.sides[0].lord;assert.equal(u.hp,FACTIONS.shu.hp*1.06);assert.equal(u.atk,FACTIONS.shu.atk*1.06);assert.equal(b.setEquipment(0,{}),false);});

test('generals accept only owned weapons and cannot share a single copy with the lord',()=>{const e={inventory:{'weapon-2':1,'armor-2':1},equipped:{weapon:'weapon-2'}};assert.equal(equipEquipment(e,{generalId:'guanyu',slot:'armor',itemId:'armor-2'}),null);assert.equal(equipEquipment(e,{generalId:'spear',slot:'weapon',itemId:'weapon-2'}),null);assert.equal(equipEquipment(e,{generalId:'guanyu',slot:'weapon',itemId:'weapon-2'}),null);const released=equipEquipment(e,{slot:'weapon',itemId:null}),armed=equipEquipment(released,{generalId:'guanyu',slot:'weapon',itemId:'weapon-2'});assert.equal(armed.generalWeapons.guanyu,'weapon-2');assert.equal(equipEquipment(armed,{generalId:'zhangfei',slot:'weapon',itemId:'weapon-2'}),null);armed.inventory['weapon-2']=2;assert.equal(equipEquipment(armed,{generalId:'zhangfei',slot:'weapon',itemId:'weapon-2'}).generalWeapons.zhangfei,'weapon-2');assert.equal(equipEquipment(armed,{generalId:'guanyu',slot:'weapon',itemId:null}).generalWeapons.guanyu,undefined);});
test('general weapon buffs apply only to the assigned general on every summon',()=>{const b=new Battle('shu',defaultDeck('shu'));b.setEquipment(0,{inventory:{'weapon-2':1},generalWeapons:{guanyu:'weapon-2'},equipped:{}});for(let i=0;i<2;i++)b.spawn(card('guanyu'),0,149,600);b.spawn(card('zhangfei'),0,454,600);b.spawn(card('spear'),0,149,650);const armed=b.units.filter(u=>u.assetId==='guanyu');assert.equal(armed.length,2);assert.ok(armed.every(u=>u.atk===card('guanyu').atk*1.06));assert.equal(b.units.find(u=>u.assetId==='zhangfei').atk,card('zhangfei').atk);assert.equal(b.units.find(u=>u.assetId==='spear').atk,card('spear').atk);assert.equal(b.sides[0].lord.atk,FACTIONS.shu.atk);assert.deepEqual(normalizeEquipment({inventory:{'weapon-2':1},equipped:{weapon:'weapon-2'},generalWeapons:{guanyu:'weapon-2',spear:'weapon-2'}}).generalWeapons,{});});
