import {Battle} from '../public/src/engine.js';
import {FACTIONS,defaultDeck,validateDeck} from '../public/src/data.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const cookie=(r,k)=>r.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(k+'='))?.slice(k.length+1);
const token=()=>crypto.randomUUID()+crypto.randomUUID();
const redirect=(url,values=[])=>new Response(null,{status:302,headers:[['Location',url],...values.map(v=>['Set-Cookie',v])]});
const jar=(name,value,age)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
const hub=env=>env.ACCOUNTS.get(env.ACCOUNTS.idFromName('global'));
async function rpc(env,path,data){return hub(env).fetch('https://internal/'+path,{method:'POST',body:JSON.stringify(data)});}
export default {async fetch(req,env){try{const url=new URL(req.url),path=url.pathname;
if(path==='/api/auth/line'){if(!env.LINE_CHANNEL_SECRET)return json({error:'LINE 登入尚未設定'},503);const state=token(),nonce=token(),auth=new URL('https://access.line.me/oauth2/v2.1/authorize');auth.search=new URLSearchParams({response_type:'code',client_id:env.LINE_CHANNEL_ID,redirect_uri:env.APP_ORIGIN+'/api/auth/callback',state,scope:'openid profile',nonce}).toString();return redirect(auth.toString(),[jar('line_state',state,600),jar('line_nonce',nonce,600)]);}
if(path==='/api/auth/callback'){const state=cookie(req,'line_state'),nonce=cookie(req,'line_nonce');if(!state||!nonce||state!==url.searchParams.get('state')||!url.searchParams.get('code'))return redirect('/?login=failed');const response=await fetch('https://api.line.me/oauth2/v2.1/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:url.searchParams.get('code'),redirect_uri:env.APP_ORIGIN+'/api/auth/callback',client_id:env.LINE_CHANNEL_ID,client_secret:env.LINE_CHANNEL_SECRET})});const tokens=await response.json();if(!response.ok||!tokens.id_token)return redirect('/?login=failed');const verified=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:tokens.id_token,client_id:env.LINE_CHANNEL_ID,nonce})});const identity=await verified.json();if(!verified.ok||!identity.sub)return redirect('/?login=failed');const session=token();await rpc(env,'login',{id:identity.sub,name:identity.name||'主公',picture:identity.picture||'',session});return redirect('/',[jar('session',session,2592000),jar('line_state','',0),jar('line_nonce','',0)]);}
if(!path.startsWith('/api/'))return env.ASSETS.fetch(req);
if(!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')!==env.APP_ORIGIN)return json({error:'來源不符'},403);
if(path==='/api/world')return rpc(env,'world',{});
const auth=await (await rpc(env,'session',{session:cookie(req,'session')})).json();if(!auth.user)return json({error:'請先 LINE 登入'},401);const user=auth.user;
if(path==='/api/me')return json({user});
if(path==='/api/logout'){await rpc(env,'logout',{session:cookie(req,'session')});return new Response('{}',{headers:{'Set-Cookie':jar('session','',0),'Content-Type':'application/json'}});}
if(path==='/api/profile'&&req.method==='POST')return rpc(env,'profile',{...await req.json(),id:user.id});
if(path==='/api/records')return rpc(env,'records',{id:user.id});
if(path==='/api/matchmaking'&&req.method==='POST'){if(!user.faction)return json({error:'請先選陣營'},400);return rpc(env,'matchmaking',{user});}
if(path==='/api/matchmaking/cancel'&&req.method==='POST')return rpc(env,'cancel',{user});
const match=path.match(/^\/api\/rooms\/([a-f0-9-]+)\/(ready|state|action)$/);if(match){const [,id,op]=match;if(op!=='state'&&req.method!=='POST')return json({error:'方法不符'},405);const listed=await (await rpc(env,'room',{id})).json();if(!listed.room)return json({error:'對戰不存在'},404);return env.MATCHES.get(env.MATCHES.idFromName(id)).fetch('https://internal/'+op,{method:'POST',body:JSON.stringify({user,room:listed.room,...(op==='action'?{action:await req.json()}:{})})});}
return json({error:'不存在'},404);
}catch{return json({error:'伺服器暫時無法處理'},500);}}};
export class Accounts {constructor(ctx,env){this.ctx=ctx;this.env=env;}
async fetch(req){const op=new URL(req.url).pathname.slice(1),d=await req.json(),s=this.ctx.storage;
if(op==='login'){let u=await s.get('user:'+d.id);u={id:d.id,name:d.name,picture:d.picture,faction:null,decks:{},tokens:1,changedAt:0,contribution:0,...u,name:d.name,picture:d.picture};await s.put('user:'+d.id,u);await s.put('session:'+d.session,{id:d.id,expires:Date.now()+2592000000});return json({ok:true});}
if(op==='session'){const t=d.session?await s.get('session:'+d.session):null;return json({user:t&&t.expires>Date.now()?await s.get('user:'+t.id):null});}
if(op==='logout'){if(d.session)await s.delete('session:'+d.session);return json({ok:true});}
if(op==='profile'){const u=await s.get('user:'+d.id);if(!u||!FACTIONS[d.faction])return json({error:'無效陣營'},400);if(u.faction&&u.faction!==d.faction){if(u.tokens<1||Date.now()-u.changedAt<2592000000)return json({error:'尚不可轉國'},400);u.tokens--;u.changedAt=Date.now();u.contribution=0;}u.faction=d.faction;for(const f of Object.keys(FACTIONS)){const deck=d.decks?.[f]||u.decks[f]||defaultDeck(f);if(!validateDeck(f,deck))return json({error:'無效牌組'},400);u.decks[f]=deck;}await s.put('user:'+d.id,u);return json({user:u});}
if(op==='world'){const users=await s.list({prefix:'user:'}),factions=Object.fromEntries(Object.keys(FACTIONS).map(f=>[f,{players:0,contribution:0,wins:0,matches:0}]));for(const u of users.values())if(factions[u.faction]){const f=factions[u.faction];f.players++;f.contribution+=u.contribution||0;}const records=await s.list({prefix:'match:'});for(const m of records.values())for(let i=0;i<2;i++){const f=factions[m.players[i].faction];f.matches++;if(m.result.winner===i)f.wins++;}return json({factions,updatedAt:Date.now()});}
if(op==='records'){const all=await s.list({prefix:'match:'});return json({records:[...all.values()].filter(m=>m.players.some(p=>p.id===d.id)).sort((a,b)=>b.at-a.at).slice(0,30)});}
if(op==='matchmaking'||op==='cancel'){return s.transaction(async tx=>{const now=Date.now(),key='assignment:'+d.user.id,assigned=await tx.get(key);if(assigned){const room=await tx.get('room:'+assigned);if(room&&room.status!=='finished'&&room.expires>now)return json({matched:true,id:room.id});await tx.delete(key);}if(op==='cancel'){await tx.delete('queue:'+d.user.id);return json({cancelled:true});}const waiting=await tx.list({prefix:'queue:'});let opponent=null;for(const [k,q] of waiting){if(q.expires<=now){await tx.delete(k);continue;}if(q.user.id!==d.user.id&&!opponent)opponent=q.user;}if(!opponent){await tx.put('queue:'+d.user.id,{user:d.user,expires:now+15000});return json({matched:false});}const room={id:crypto.randomUUID(),host:opponent,guest:d.user,status:'waiting',expires:now+600000};await tx.delete('queue:'+opponent.id);await tx.delete('queue:'+d.user.id);await tx.put('room:'+room.id,room);await tx.put('assignment:'+opponent.id,room.id);await tx.put(key,room.id);return json({matched:true,id:room.id});});}
if(op==='room')return json({room:await s.get('room:'+d.id)});
if(op==='status'){const r=await s.get('room:'+d.id);if(r){r.status=d.status;await s.put('room:'+d.id,r);}return json({ok:true});}
if(op==='finish'){await s.transaction(async tx=>{if(await tx.get('match:'+d.id))return;await tx.put('match:'+d.id,d);for(let i=0;i<2;i++){const u=await tx.get('user:'+d.players[i].id);if(u){u.contribution=(u.contribution||0)+(d.result.winner===i?10:2);await tx.put('user:'+u.id,u);}}});const room=await s.get('room:'+d.id);if(room){room.status='finished';await s.put('room:'+d.id,room);}return json({ok:true});}
return json({error:'不存在'},404);}}
export class Match {constructor(ctx,env){this.ctx=ctx;this.env=env;this.battle=null;this.players=[];this.events=[];this.last=0;this.finished=false;ctx.blockConcurrencyWhile(async()=>{const saved=await ctx.storage.get('game');if(saved){this.players=saved.players;this.events=saved.events;this.last=saved.last;this.id=saved.id;this.finished=saved.finished;this.ready=saved.ready||[];if(saved.battle){this.battle=Object.assign(Object.create(Battle.prototype),saved.battle);this.battle.random=Math.random;this.battle.ai=()=>{};for(let i=0;i<2;i++)this.battle.sides[i].lord=this.battle.units.find(u=>u.id===saved.lordIds[i]);}}});}
async persist(){await this.ctx.storage.put('game',{id:this.id,players:this.players,events:this.events,last:this.last,finished:this.finished,ready:this.ready||[],battle:this.battle?JSON.parse(JSON.stringify(this.battle)):null,lordIds:this.battle?.sides.map(p=>p.lord.id)});}
async fetch(req){const {user,room,action}=await req.json(),op=new URL(req.url).pathname.slice(1);if(room.expires<Date.now()&&!this.battle)return json({error:'配對已過期'},410);if(!this.players.length){this.id=room.id;this.players=[room.host,room.guest];await this.persist();}let side=this.players.findIndex(p=>p.id===user.id);
if(side<0)return json({error:'不屬於此對戰'},403);
if(op==='ready'&&!this.battle){this.ready ||= [];if(!this.ready.includes(user.id))this.ready.push(user.id);if(this.ready.length===2){const [a,b]=this.players;this.battle=new Battle(a.faction,a.decks[a.faction]||defaultDeck(a.faction),b.faction);this.battle.sides[1].queue=[...(b.decks[b.faction]||defaultDeck(b.faction))];this.battle.lordSpawnY=[762,100];this.battle.sides[0].lord.y=762;this.battle.sides[1].lord.y=100;this.battle.ai=()=>{};this.last=Date.now();await rpc(this.env,'status',{id:this.id,status:'playing'});await this.ctx.storage.setAlarm(Date.now()+100);}await this.persist();}
if(op==='action'){if(!this.battle||this.battle.result||this.battle.pauseRemaining>0)return json({error:'未在戰鬥'},409);this.rate ||=new Map();const now=Date.now();if(now-(this.rate.get(user.id)||0)<60)return json({error:'操作過快'},429);this.rate.set(user.id,now);let ok=false;const cardId=action.type==='play'?this.battle.hand(side)[action.index]?.id:undefined;if(action.type==='move'&&Number.isFinite(action.x)&&Number.isFinite(action.y)){this.battle.moveLord(side,action.x,action.y);ok=true;}else if(action.type==='play'&&Number.isInteger(action.index))ok=this.battle.play(side,action.index,action.x,action.y);else if(action.type==='ultimate')ok=this.battle.ultimate(side);if(ok)this.events.push({at:this.battle.elapsed,side,type:action.type,index:action.index,cardId,x:action.x,y:action.y});return json({ok});}
const b=this.battle;return json({side,players:this.players.map(p=>({name:p.name,picture:p.picture,faction:p.faction})),battle:b?{time:b.time,elapsed:b.elapsed,pauseRemaining:b.pauseRemaining,cinematic:b.cinematic,units:b.units,buildings:b.buildings,effects:b.effects,result:b.result,sides:b.sides.map((p,i)=>({...p,queue:i===side?p.queue:[],lord:p.lord}))}:null});}
async alarm(){if(!this.battle||this.finished)return;this.battle.ai=()=>{};const now=Date.now(),steps=Math.min(20,Math.max(1,Math.round((now-this.last)/100)));this.last=now;for(let i=0;i<steps&&!this.battle.result;i++)this.battle.update(.1);if(this.battle.result){await rpc(this.env,'finish',{id:this.id,at:Date.now(),players:this.players.map(p=>({id:p.id,name:p.name,faction:p.faction,deck:p.decks[p.faction]})),result:this.battle.result,buildings:this.battle.buildings,events:this.events});this.finished=true;}await this.persist();if(!this.finished)await this.ctx.storage.setAlarm(Date.now()+100);}}
