import {normalizeEquipment,equipEquipment,equipmentDrop} from '../public/src/equipment.js';
import {territoryShares,PROVINCES,TERRITORY_KEYS} from '../public/src/territory.js';
import {campaignPeriod,newCampaign,campaignSummary,contributionAwards,resolveProvince,localDay} from './campaign.js';
import {Battle,placementPoint} from '../public/src/engine.js';
import {FACTIONS,card,defaultDeck,validateDeck} from '../public/src/data.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const cookie=(r,k)=>r.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(k+'='))?.slice(k.length+1);
const token=()=>crypto.randomUUID()+crypto.randomUUID();
const redirect=(url,values=[])=>new Response(null,{status:302,headers:[['Location',url],...values.map(v=>['Set-Cookie',v])]});
const jar=(name,value,age)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
const hub=env=>env.ACCOUNTS.get(env.ACCOUNTS.idFromName('global'));
async function rpc(env,path,data){return hub(env).fetch('https://internal/'+path,{method:'POST',body:JSON.stringify(data)});}
export default {async fetch(req,env){try{const url=new URL(req.url),path=url.pathname;
if(path==='/api/auth/line'){if(!env.LINE_CHANNEL_SECRET)return json({error:'LINE 登入尚未設定'},503);const state=token(),nonce=token(),appClient=url.searchParams.get('client')==='app',auth=new URL('https://access.line.me/oauth2/v2.1/authorize');auth.search=new URLSearchParams({response_type:'code',client_id:env.LINE_CHANNEL_ID,redirect_uri:env.APP_ORIGIN+'/api/auth/callback',state,scope:'openid profile',nonce}).toString();return redirect(auth.toString(),[jar('line_state',state,600),jar('line_nonce',nonce,600),jar('line_client',appClient?'app':'web',600)]);}
if(path==='/api/auth/callback'){const state=cookie(req,'line_state'),nonce=cookie(req,'line_nonce'),appClient=cookie(req,'line_client')==='app';if(!state||!nonce||state!==url.searchParams.get('state')||!url.searchParams.get('code'))return redirect('/?login=failed');const response=await fetch('https://api.line.me/oauth2/v2.1/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:url.searchParams.get('code'),redirect_uri:env.APP_ORIGIN+'/api/auth/callback',client_id:env.LINE_CHANNEL_ID,client_secret:env.LINE_CHANNEL_SECRET})});const tokens=await response.json();if(!response.ok||!tokens.id_token)return redirect('/?login=failed');const verified=await fetch('https://api.line.me/oauth2/v2.1/verify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:tokens.id_token,client_id:env.LINE_CHANNEL_ID,nonce})});const identity=await verified.json();if(!verified.ok||!identity.sub)return redirect('/?login=failed');const session=token();await rpc(env,'login',{id:identity.sub,name:identity.name||'主公',picture:identity.picture||'',session});const clear=[jar('line_state','',0),jar('line_nonce','',0),jar('line_client','',0)];if(appClient){const ticket=token();await rpc(env,'app-ticket-create',{ticket,session});return redirect('samkokshowdown://auth?ticket='+encodeURIComponent(ticket),clear);}return redirect('/',[jar('session',session,2592000),...clear]);}
if(!path.startsWith('/api/'))return env.ASSETS.fetch(req);
if(!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')!==env.APP_ORIGIN)return json({error:'來源不符'},403);
if(path==='/api/auth/app-session'&&req.method==='POST'){const {ticket}=await req.json(),result=await (await rpc(env,'app-ticket-consume',{ticket})).json();if(!result.session)return json({error:'登入票券無效或已過期'},401);return new Response(JSON.stringify({ok:true}),{headers:{'Set-Cookie':jar('session',result.session,2592000),'Content-Type':'application/json','Cache-Control':'no-store'}});}
if(path==='/api/world')return rpc(env,'world',{});
if(path==='/api/leaderboard'&&req.method==='GET')return rpc(env,'leaderboard',{});
const auth=await (await rpc(env,'session',{session:cookie(req,'session')})).json();if(!auth.user)return json({error:'請先 LINE 登入'},401);const user=auth.user;
if(path==='/api/me')return json({user,match:auth.match||null});
if(path==='/api/logout'&&req.method==='POST'){await rpc(env,'logout',{session:cookie(req,'session')});return new Response('{}',{headers:{'Set-Cookie':jar('session','',0),'Content-Type':'application/json'}});}
if(path==='/api/profile'&&req.method==='POST')return rpc(env,'profile',{...await req.json(),id:user.id});
if(path==='/api/equipment'){if(req.method==='GET')return json({equipment:normalizeEquipment(user.equipment)});if(req.method==='POST')return rpc(env,'equipment',{...await req.json(),id:user.id});return json({error:'方法不符'},405);}
if(path==='/api/records')return rpc(env,'records',{id:user.id});
const log=path.match(/^\/api\/records\/([a-f0-9-]+)\/events$/);if(log)return rpc(env,'record-events',{userId:user.id,id:log[1],offset:Number(url.searchParams.get('offset')||0)});
if(path==='/api/matchmaking'&&req.method==='POST'){if(!user.faction)return json({error:'請先選陣營'},400);return rpc(env,'matchmaking',{...await req.json(),user});}
if(path==='/api/matchmaking/cancel'&&req.method==='POST')return rpc(env,'cancel',{user});
const match=path.match(/^\/api\/rooms\/([a-f0-9-]+)\/(ready|state|action|stream)$/);if(match){const [,id,op]=match;if(op==='stream'&&(req.method!=='GET'||req.headers.get('Upgrade')?.toLowerCase()!=='websocket'))return json({error:'需 WebSocket 連線'},426);if(op==='stream'&&req.headers.get('Origin')!==env.APP_ORIGIN)return json({error:'來源不符'},403);if(!['state','stream'].includes(op)&&req.method!=='POST')return json({error:'方法不符'},405);const listed=await (await rpc(env,'room',{id})).json();if(!listed.room)return json({error:'對戰不存在'},404);if(op==='stream')return env.MATCHES.get(env.MATCHES.idFromName(id)).fetch('https://internal/stream?user='+encodeURIComponent(user.id),{headers:{Upgrade:'websocket'}});return env.MATCHES.get(env.MATCHES.idFromName(id)).fetch('https://internal/'+op,{method:'POST',body:JSON.stringify({user,room:listed.room,...(op==='action'?{action:await req.json()}:{})})});}
return json({error:'不存在'},404);
}catch{return json({error:'伺服器暫時無法處理'},500);}}};
const activeRoom=(r,now)=>r&&['waiting','playing'].includes(r.status)&&r.expires>now&&(r.status==='playing'||(r.readyDeadline||r.expires)>now);
function normalizeUser(u,now=Date.now()){if(!u)return null;u.decks ||= {};u.equipment=normalizeEquipment(u.equipment);if(u.tokens<1&&now-(u.changedAt||0)>=2592000000)u.tokens=1;const period=campaignPeriod(now);if(u.campaignId!==period.id){u.campaignId=period.id;u.contribution=0;}return u;}
export class Accounts {
  constructor(ctx,env){this.ctx=ctx;this.env=env;}
  async cancelRoom(tx,r){r.status='cancelled';await tx.put('room:'+r.id,r);for(const p of [r.host,r.guest])if(p&&await tx.get('assignment:'+p.id)===r.id)await tx.delete('assignment:'+p.id);}
  async fetch(req){const op=new URL(req.url).pathname.slice(1),d=await req.json(),s=this.ctx.storage,now=Date.now();
    if(op==='login'){return s.transaction(async tx=>{const u=normalizeUser({id:d.id,name:d.name,picture:d.picture,faction:null,decks:{},tokens:1,changedAt:0,contribution:0,...await tx.get('user:'+d.id),name:d.name,picture:d.picture},now);await tx.put('user:'+d.id,u);await tx.put('session:'+d.session,{id:d.id,expires:now+2592000000});return json({ok:true});});}
    if(op==='session'){const t=d.session?await s.get('session:'+d.session):null,user=t&&t.expires>now?normalizeUser(await s.get('user:'+t.id),now):null,id=user?await s.get('assignment:'+user.id):null,r=id?await s.get('room:'+id):null;return json({user,match:activeRoom(r,now)?{id:r.id,province:r.province,status:r.status}:null});}
    if(op==='app-ticket-create'){if(!d.ticket||!d.session)return json({error:'無效登入票券'},400);await s.put('app-ticket:'+d.ticket,{session:d.session,expires:now+120000});return json({ok:true});}
    if(op==='app-ticket-consume'){if(!d.ticket)return json({});const key='app-ticket:'+d.ticket,t=await s.get(key);await s.delete(key);return json({session:t&&t.expires>now?t.session:null});}
    if(op==='logout'){if(d.session)await s.delete('session:'+d.session);return json({ok:true});}
    if(op==='profile')return s.transaction(async tx=>{const u=normalizeUser(await tx.get('user:'+d.id),now);if(!u||!Object.hasOwn(FACTIONS,d.faction))return json({error:'無效陣營'},400);const assigned=await tx.get('assignment:'+u.id),room=assigned?await tx.get('room:'+assigned):null;if(activeRoom(room,now))return json({error:'對戰結束後才能修改'},409);if(u.faction&&u.faction!==d.faction){if(u.tokens<1||now-u.changedAt<2592000000)return json({error:'轉國間隔需滿 30 天'},400);u.tokens--;u.changedAt=now;u.contribution=0;}u.faction=d.faction;const decks={};for(const f of TERRITORY_KEYS){const deck=d.decks?.[f]||u.decks[f]||defaultDeck(f);if(!validateDeck(f,deck))return json({error:'無效牌組'},400);decks[f]=deck;}u.decks=decks;await tx.put('user:'+u.id,u);return json({user:u});});
    if(op==='equipment')return s.transaction(async tx=>{const u=normalizeUser(await tx.get('user:'+d.id),now);if(!u)return json({error:'請先登入'},401);const assigned=await tx.get('assignment:'+u.id),room=assigned?await tx.get('room:'+assigned):null,queue=await tx.get('queue:'+u.id);if(activeRoom(room,now)||queue?.expires>now)return json({error:'請先結束配對或對戰，再更換裝備'},409);const equipment=equipEquipment(u.equipment,{slot:d.slot,itemId:d.itemId,generalId:d.generalId??null});if(!equipment)return json({error:'裝備不足、欄位不符，或武將僅可裝備武器'},400);u.equipment=equipment;await tx.put('user:'+u.id,u);return json({equipment:u.equipment});});
    if(op==='world'){const period=campaignPeriod(now),c=await s.get('campaign:'+period.id)||newCampaign(now),users=await s.list({prefix:'user:'}),factions=structuredClone(c.factions);for(const f of TERRITORY_KEYS)factions[f].players=0;for(const u of users.values())if(factions[u.faction])factions[u.faction].players++;const archive=await s.list({prefix:'campaign:'}),previous=[...archive.values()].filter(c=>c.end<=now).sort((a,b)=>b.end-a.end)[0];return json({...campaignSummary(c),factions,strength:territoryShares(factions),provinces:c.provinces,previous:previous?campaignSummary(previous):null,updatedAt:now});}
    if(op==='leaderboard'){const scores=new Map();let startAfter;while(true){const page=await s.list({prefix:'match:',limit:500,...(startAfter?{startAfter}:{})});for(const m of page.values()){if(!Array.isArray(m.players)||m.players.length!==2||m.players[0].id===m.players[1].id||![-1,0,1].includes(m.result?.winner))continue;for(let i=0;i<2;i++){const p=m.players[i];if(!p.id)continue;let row=scores.get(p.id);if(!row){row={id:p.id,name:p.name,faction:p.faction,matches:0,wins:0,at:0,counts:{}};scores.set(p.id,row);}row.matches++;for(const id of new Set(p.deck||[]))if(card(id))row.counts[id]=(row.counts[id]||0)+1;if(m.result.winner===i)row.wins++;if(m.at>=row.at){row.name=p.name;row.faction=p.faction;row.at=m.at;}}}if(page.size<500)break;startAfter=[...page.keys()].at(-1);}const rows=[...scores.values()].map(r=>({...r,rate:r.wins/r.matches})),tie=(a,b)=>b.wins-a.wins||b.matches-a.matches||a.id.localeCompare(b.id),publicRows=rows=>rows.map(({id,at,counts,...r},i)=>({...r,rank:i+1,favorites:Object.fromEntries(['general','spell','troop'].map(type=>[type,Object.keys(counts).filter(id=>card(id)?.type===type).sort((a,b)=>counts[b]-counts[a]||a.localeCompare(b))[0]||null]))}));return json({rows:publicRows(rows.sort((a,b)=>b.wins-a.wins||b.rate-a.rate||tie(a,b))),updatedAt:now});}
    if(op==='records'){let ids=await s.get('history:'+d.id);if(!ids){const all=await s.list({prefix:'match:'});ids=[...all.values()].filter(m=>m.players.some(p=>p.id===d.id)).sort((a,b)=>b.at-a.at).slice(0,100).map(m=>m.id);await s.put('history:'+d.id,ids);}const records=(await Promise.all(ids.slice(0,30).map(id=>s.get('match:'+id)))).filter(Boolean).map(m=>({...m,eventCount:m.eventCount??m.events?.length??0,events:undefined}));return json({records});}
    if(op==='record-events'){const m=await s.get('match:'+d.id);if(!m||!m.players.some(p=>p.id===d.userId))return json({error:'戰績不存在'},404);const offset=Number.isInteger(d.offset)&&d.offset>=0?Math.floor(d.offset/100)*100:0,events=m.events?m.events.slice(offset,offset+100):await s.get('match-events:'+d.id+':'+String(offset/100).padStart(4,'0'))||[];return json({events,next:offset+100<(m.eventCount??m.events?.length??0)?offset+100:null});}
    if(op==='matchmaking'||op==='cancel')return s.transaction(async tx=>{const user=normalizeUser(await tx.get('user:'+d.user.id)||d.user,now);if(!Object.hasOwn(FACTIONS,user.faction))return json({error:'請先選陣營'},400);if(d.province&&!PROVINCES.some(p=>p.id===d.province))return json({error:'無效州份'},400);const key='assignment:'+user.id,assigned=await tx.get(key),r=assigned?await tx.get('room:'+assigned):null;if(activeRoom(r,now)){if(op==='cancel'&&r.status==='waiting'){await this.cancelRoom(tx,r);return json({cancelled:true});}return json({matched:true,id:r.id,province:r.province,readyDeadline:r.readyDeadline});}if(r&&r.status==='waiting')await this.cancelRoom(tx,r);if(assigned)await tx.delete(key);if(op==='cancel'){await tx.delete('queue:'+user.id);return json({cancelled:true});}const waiting=await tx.list({prefix:'queue:'});let opponent=null;for(const [k,q] of [...waiting].sort((a,b)=>(a[1].enteredAt||0)-(b[1].enteredAt||0))){if(q.expires<=now){await tx.delete(k);continue;}if(q.user.id===user.id)continue;if((d.province||q.province)&&q.user.faction===user.faction)continue;if(d.province&&q.province&&d.province!==q.province)continue;if(!opponent)opponent=q;}if(!opponent){const old=await tx.get('queue:'+user.id);await tx.put('queue:'+user.id,{user,province:d.province||null,enteredAt:old?.enteredAt||now,expires:now+15000});return json({matched:false});}const id=crypto.randomUUID(),province=d.province||opponent.province||PROVINCES[parseInt(id.slice(0,4),16)%PROVINCES.length].id,room={id,host:opponent.user,guest:user,province,status:'waiting',readyDeadline:now+30000,expires:now+1800000};await tx.delete('queue:'+opponent.user.id);await tx.delete('queue:'+user.id);await tx.put('room:'+id,room);await tx.put('assignment:'+opponent.user.id,id);await tx.put(key,id);return json({matched:true,id,province,readyDeadline:room.readyDeadline});});
    if(op==='room')return json({room:await s.get('room:'+d.id)});
    if(op==='status')return s.transaction(async tx=>{const r=await tx.get('room:'+d.id);if(!r)return json({error:'對戰不存在'},404);if(d.status==='playing'&&(!activeRoom(r,now)||r.status!=='waiting'))return json({error:'配對已取消或過期'},410);r.status=d.status;await tx.put('room:'+d.id,r);if(d.status==='cancelled')await this.cancelRoom(tx,r);return json({ok:true});});
    if(op==='finish')return s.transaction(async tx=>{const old=await tx.get('match:'+d.id);if(old)return json({record:old});const c=await tx.get('campaign:'+campaignPeriod(now).id)||newCampaign(now),pair=[...d.players.map(p=>p.id)].sort().join('|'),pairKey='pair:'+localDay(now)+':'+pair,repeats=await tx.get(pairKey)||0,{awards,multiplier,reason}=contributionAwards(d,repeats);if(multiplier)await tx.put(pairKey,repeats+1);const room=await tx.get('room:'+d.id),province=room?.province||d.province,war=d.result.winner>=0?resolveProvince(c,province,d.players[d.result.winner].faction,awards[d.result.winner],now):null;const lootKey='loot-pair:'+localDay(now)+':'+pair,lootRepeats=await tx.get(lootKey)||0,loot=room?.status==='playing'?equipmentDrop(d,lootRepeats):{eligible:false,reason:'非有效真人對戰'};if(loot.eligible)await tx.put(lootKey,lootRepeats+1);const record={...d,equipmentDrops:loot.items||[null,null],equipmentReason:loot.reason||'',events:undefined,eventCount:d.events.length,at:now,province,campaignId:c.id,awards,multiplier,contributionReason:reason,war};for(let i=0;i<d.events.length;i+=100)await tx.put('match-events:'+d.id+':'+String(i/100).padStart(4,'0'),d.events.slice(i,i+100));await tx.put('match:'+d.id,record);for(let i=0;i<2;i++){const p=d.players[i],history=await tx.get('history:'+p.id);if(history)await tx.put('history:'+p.id,[d.id,...history.filter(id=>id!==d.id)].slice(0,100));const f=c.factions[p.faction];f.contribution+=awards[i];f.matches++;if(d.result.winner===i)f.wins++;const u=normalizeUser(await tx.get('user:'+p.id),now);if(u&&u.faction===p.faction){u.contribution+=awards[i];if(loot.eligible){const itemId=loot.items[i];u.equipment.inventory[itemId]=Math.min(Number.MAX_SAFE_INTEGER,(u.equipment.inventory[itemId]||0)+1);}await tx.put('user:'+u.id,u);}if(await tx.get('assignment:'+p.id)===d.id)await tx.delete('assignment:'+p.id);}c.updatedAt=now;await tx.put('campaign:'+c.id,c);if(room){room.status='finished';await tx.put('room:'+d.id,room);}return json({record});});
    return json({error:'不存在'},404);
  }
}
export class Match {
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.battle=null;this.players=[];this.events=[];this.last=0;this.finished=false;this.ready=[];this.lastSeen=[0,0];this.receipts=[];this.receiptCounter=0;this.persistedEvents=0;this.persistedReceipts=0;this.sequence=0;this.lock=Promise.resolve();ctx.blockConcurrencyWhile(async()=>{const saved=await ctx.storage.get('game');if(saved){Object.assign(this,{players:saved.players,events:saved.events,last:saved.last,id:saved.id,finished:saved.finished,ready:saved.ready||[],lastSeen:saved.lastSeen||[Date.now(),Date.now()],receipts:saved.receipts||[],province:saved.province});if(saved.eventCount!==undefined){const chunks=await ctx.storage.list({prefix:'events:'});this.events=[...chunks].sort((a,b)=>a[0].localeCompare(b[0])).flatMap(([,events])=>events).slice(0,saved.eventCount);this.persistedEvents=this.events.length;}const receipts=await ctx.storage.get('receipts');this.receipts=receipts||saved.receipts||[];this.sequence=saved.sequence||0;this.receiptCounter=saved.receiptCounter||this.receipts.length;this.persistedReceipts=receipts?this.receiptCounter:0;if(saved.battle){this.battle=Object.assign(Object.create(Battle.prototype),saved.battle);this.battle.random=Math.random;this.battle.aiTimer=Infinity;for(let i=0;i<2;i++)this.battle.sides[i].lord=this.battle.units.find(u=>u.id===saved.lordIds[i]);}}});}
  async exclusive(fn){const previous=this.lock;let release;this.lock=new Promise(r=>release=r);await previous;try{return await fn();}finally{release();}}
  async persist(){const eventCount=this.events.length,receiptCounter=this.receiptCounter;await this.ctx.storage.transaction(async tx=>{if(eventCount>this.persistedEvents)for(let i=Math.floor(this.persistedEvents/100)*100;i<eventCount;i+=100)await tx.put('events:'+String(i/100).padStart(4,'0'),this.events.slice(i,i+100));if(receiptCounter!==this.persistedReceipts)await tx.put('receipts',this.receipts);await tx.put('game',{id:this.id,players:this.players,eventCount,receiptCounter,sequence:this.sequence,last:this.last,finished:this.finished,ready:this.ready,lastSeen:this.lastSeen,province:this.province,battle:this.battle?JSON.parse(JSON.stringify(this.battle)):null,lordIds:this.battle?.sides.map(p=>p.lord.id)});});this.persistedEvents=eventCount;this.persistedReceipts=receiptCounter;}

  async finish(){if(this.finished||!this.battle?.result)return;const r=await rpc(this.env,'finish',{id:this.id,at:Date.now(),province:this.province,players:this.players.map(p=>({id:p.id,name:p.name,faction:p.faction,deck:p.decks[p.faction]||defaultDeck(p.faction)})),result:this.battle.result,buildings:this.battle.buildings,events:this.events});if(!r.ok)throw Error('結算失敗');const {record}=await r.json();this.battle.result={...record.result,awards:record.awards,war:record.war,contributionReason:record.contributionReason,equipmentDrops:record.equipmentDrops,equipmentReason:record.equipmentReason};this.finished=true;}
  async fetch(req){return this.exclusive(()=>this.handle(req));}
  async handle(req){const url=new URL(req.url),op=url.pathname.slice(1),now=Date.now();if(op==='stream'&&!this.battle)return json({error:'未在戰鬥'},409);const {user,room,action}=op==='stream'?{user:{id:url.searchParams.get('user')},room:{id:this.id,host:this.players[0],guest:this.players[1]}}:await req.json();if(![room.host?.id,room.guest?.id].includes(user.id))return json({error:'不屬於此對戰'},403);if(!this.battle&&(room.status==='cancelled'||room.expires<=now||(room.readyDeadline||room.expires)<=now)){await rpc(this.env,'status',{id:room.id,status:'cancelled'});return json({error:'配對已取消或逾時',retry:true},410);}if(!this.players.length){this.id=room.id;this.players=[room.host,room.guest];this.province=room.province;await this.ctx.storage.setAlarm(room.readyDeadline||room.expires);}const side=this.players.findIndex(p=>p.id===user.id);if(this.battle&&!this.finished&&this.lastSeen[side]&&now-this.lastSeen[side]>=30000){this.battle.finish(this.lastSeen.every(t=>now-t>=30000)?-1:1-side,'disconnect');this.sequence++;await this.finish();await this.persist();this.broadcast(now);}this.lastSeen[side]=now;
    if(op==='ready'&&!this.battle){if(!this.ready.includes(user.id))this.ready.push(user.id);if(this.ready.length===2){const r=await rpc(this.env,'status',{id:this.id,status:'playing'});if(!r.ok)return r;const [a,b]=this.players;this.battle=new Battle(a.faction,a.decks[a.faction]||defaultDeck(a.faction),b.faction);this.battle.sides[1].queue=[...(b.decks[b.faction]||defaultDeck(b.faction))];for(let side=0;side<2;side++)this.battle.setEquipment(side,this.players[side].equipment);this.battle.aiTimer=Infinity;this.last=now;this.lastSeen=[now,now];await this.ctx.storage.setAlarm(now+100);}await this.persist();}
    if(op==='action'){const id=action?.id;if(!id||typeof id!=='string'||id.length>80)return json({error:'無效操作編號'},400);const duplicate=this.receipts.find(r=>r.id===id&&r.side===side);if(duplicate)return json({...this.state(side,now,room.readyDeadline),duplicate:true});if(!this.battle||this.battle.result)return json({error:'未在戰鬥'},409);if(action.type!=='resign'&&(this.battle.pauseRemaining>0||this.lastSeen.some(t=>now-t>3000)))return json({error:'戰鬥暫停中'},409);this.rate ||= new Map();const rateKey=user.id+':'+action.type;if(now-(this.rate.get(rateKey)||0)<60)return json({error:'操作過快'},429);let ok=false;const cardId=action.type==='play'?this.battle.hand(side)[action.index]?.id:undefined;if(action.type==='resign'){this.battle.finish(1-side,'surrender');ok=true;}else if(action.type==='move'&&Number.isFinite(action.x)&&Number.isFinite(action.y)&&this.battle.sides[side].lord.hp>0){ok=this.battle.moveLord(side,action.x,action.y);}else if(action.type==='play'&&Number.isInteger(action.index)&&cardId===action.cardId)ok=this.battle.play(side,action.index,action.x,action.y);else if(action.type==='ultimate')ok=this.battle.ultimate(side);if(!ok)return json({error:action.type==='play'?'出牌未成功：請確認士氣、位置與手牌':'操作未成功'},409);this.rate.set(rateKey,now);this.receipts.push({id,side});this.receipts=this.receipts.slice(-1024);this.receiptCounter++;const placed=action.type==='play'?placementPoint(action.x,action.y,side,cardId?card(cardId):null):null;this.events.push({at:this.battle.elapsed,side,type:action.type,index:action.index,cardId,x:action.type==='move'?this.battle.sides[side].lord.destination.x:placed?.x??action.x,y:action.type==='move'?this.battle.sides[side].lord.destination.y:placed?.y??action.y});this.sequence++;await this.finish();await this.persist();}
    if(op==='stream'){
      const [client,server]=Object.values(new WebSocketPair());
      for(const ws of this.ctx.getWebSockets(String(side)))ws.close(1000,'replaced');
      this.ctx.acceptWebSocket(server,[String(side)]);server.serializeAttachment({side,userId:user.id});
      server.send(JSON.stringify(this.state(side,now,room.readyDeadline)));
      return new Response(null,{status:101,webSocket:client});
    }
    if(op==='action')this.broadcast(now);
    return json(this.state(side,now,room.readyDeadline));
  }
  state(side,now=Date.now(),readyDeadline){
    const b=this.battle,missing=this.lastSeen.map(t=>t?Math.max(0,now-t):0);
    return {ok:true,side,province:this.province,readyDeadline,disconnect:missing.map(t=>t>3000?Math.max(0,30-Math.floor(t/1000)):null),players:this.players.map(p=>({name:p.name,picture:p.picture,faction:p.faction})),battle:b?{snapshotSequence:this.sequence,stateRevision:this.receiptCounter,time:b.time,elapsed:b.elapsed,pauseRemaining:b.pauseRemaining,cinematic:b.cinematic,units:b.units,buildings:b.buildings,effects:b.effects,result:this.finished?b.result:null,sides:b.sides.map((p,i)=>({...p,queue:i===side?p.queue:[],lord:p.lord}))}:null};
  }
  broadcast(now=Date.now()){
    for(const ws of this.ctx.getWebSockets?.()||[]){const member=ws.deserializeAttachment();if(!member||this.players[member.side]?.id!==member.userId)continue;try{ws.send(JSON.stringify(this.state(member.side,now)));}catch{try{ws.close(1011,'send failed');}catch{}}}
  }
  async webSocketMessage(ws,message){return this.exclusive(async()=>{
    const member=ws.deserializeAttachment();if(!member||this.players[member.side]?.id!==member.userId){ws.close(1008,'membership');return;}
    if(typeof message!=='string'||message.length>100){ws.close(1008,'invalid heartbeat');return;}
    let data;try{data=JSON.parse(message);}catch{ws.close(1008,'invalid heartbeat');return;}
    if(!data||data.type!=='ping')return;
    const now=Date.now();if(!this.finished&&this.lastSeen[member.side]&&now-this.lastSeen[member.side]>=30000){this.battle?.finish(this.lastSeen.every(t=>now-t>=30000)?-1:1-member.side,'disconnect');await this.finish();await this.persist();}
    this.lastSeen[member.side]=now;ws.send(JSON.stringify({type:'pong'}));
  });}
  async webSocketClose(ws,code,reason){ws.close(code,reason);}
  async webSocketError(ws){ws.close(1011,'connection error');}

  async alarm(){return this.exclusive(async()=>{if(this.finished)return;const now=Date.now();if(!this.battle){if(this.id)await rpc(this.env,'status',{id:this.id,status:'cancelled'});return;}const expired=this.lastSeen.map(t=>now-t>=30000);if(expired.some(Boolean))this.battle.finish(expired.every(Boolean)?-1:expired[0]?1:0,'disconnect');const paused=this.lastSeen.some(t=>now-t>3000),steps=Math.min(20,Math.max(1,Math.round((now-this.last)/100)));this.last=now;if(!paused&&!this.battle.result){this.battle.aiTimer=Infinity;for(let i=0;i<steps&&!this.battle.result;i++)this.battle.update(.1);}this.sequence++;await this.finish();await this.persist();this.broadcast(now);if(!this.finished)await this.ctx.storage.setAlarm(now+100);});}
}

